global_settings:
  bind_address: "0.0.0.0:8080"
upstream_services:
- name: ip-location-service
  http_service:
    address: "https://ipapi.co"
    calls:
    - operation_id: "getLocation"
      description: "Gets the location of a given IP address."
      endpoint_path: "/{ip}/{format}/"
      method: "HTTP_METHOD_GET"
      parameters:
      - name: "ip"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "format"
        in: "path"
        required: true
        schema:
          type: "string"
- name: time-service
  http_service:
    address: "http://worldtimeapi.org"
    calls:
    - operation_id: "get_time_by_ip"
      description: "Gets the current time for a given IP address."
      endpoint_path: "/api/ip/{ip}"
      method: "HTTP_METHOD_GET"
      parameters:
      - name: "ip"
        in: "path"
        required: true
        schema:
          type: "string"
