global_settings:
  bind_address: "0.0.0.0:8080"
upstream_services:
- name: time-service
  http_service:
    address: "http://localhost:8081"
    calls:
    - operation_id: "GET/time"
      endpoint_path: "/time"
      method: "HTTP_METHOD_GET"