global_settings:
  bind_address: "0.0.0.0:8080"
upstream_services:
- name: hello-service
  mcp_service:
    stdio_connection:
      command: "examples/upstream/command/server/hello.sh"
      args:
        - "World"