global_settings:
  bind_address: "0.0.0.0:8080"
upstream_services:
- name: hello-service
  mcp_service:
    stdio_connection:
      command: "./build/venv/bin/python"
      args:
        - "-u"
        - "examples/upstream/command/server/main.py"
        - "--mcp-stdio"
      working_directory: "."
