# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

upstream_services:
  - name: "docker-http-echo"
    command_line_service:
      command: "echo"
      tools:
        - name: "echo"
          description: "Echoes back the request body."
          call_id: "echo"
          input_schema: {}
      calls:
        echo:
          args: ['{"message": "Hello MCP"}']
      # health_check:
      #   timeout: "2s"

global_settings:
  api_key: "demo-key"
