load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "file-upload_lib",
    srcs = ["main.go"],
    importpath = "github.com/mcpany/core/server/examples/upstream_service_demo/file-upload",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "file-upload",
    embed = [":file-upload_lib"],
    visibility = ["//visibility:public"],
)
