version: "2"

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - govet
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unused

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - "errcheck"
  skip-files:
    - ".*\\.pb\\.go$"
