// Copyright 2025 Author(s) of MCP Any
// SPDX-License-Identifier: Apache-2.0

// Package framework provides testing framework utilities.
package framework

import (
	"time"

	"github.com/mcpany/core/server/tests/integration"
)

// Re-exporting these from the integration package so that framework users
// don't need to import both.
var (
	// Summary: Defines FindFreePort.
	FindFreePort          = integration.FindFreePort
	// Summary: Defines NewManagedProcess.
	NewManagedProcess     = integration.NewManagedProcess
	// Summary: Defines WaitForTCPPort.
	WaitForTCPPort        = integration.WaitForTCPPort
	// Summary: Defines GetProjectRoot.
	GetProjectRoot        = integration.GetProjectRoot
	// Summary: Defines ServiceStartupTimeout.
	ServiceStartupTimeout = 15 * time.Second
)

// AITool represents an AI tool used in testing.
// AITool ...
//
// Summary: Represents a AITool.
type AITool interface {
	// Install performs any necessary installation steps for the AI tool.
	// Install ...
	//
	// Summary: Executes Install operation.
	//
	// Parameters:
	//   - None.
	//
	// Returns:
	//   - None.
	//
	// Errors:
	//   - None.
	//
	// Side Effects:
	//   - None.
	Install()

	// AddMCP registers a new MCP server with the AI tool.
	//
	// Parameters:
	//   name: The name to assign to the MCP server.
	//   endpoint: The URL or address of the MCP server.
	// AddMCP ...
	//
	// Summary: Initializes AddMCP operation.
	//
	// Parameters:
	//   - name: name. The name parameter.
	//   - endpoint: string. A string value.
	//
	// Returns:
	//   - None.
	//
	// Errors:
	//   - None.
	//
	// Side Effects:
	//   - None.
	AddMCP(name, endpoint string)

	// RemoveMCP unregisters an MCP server from the AI tool.
	//
	// Parameters:
	//   name: The name of the MCP server to remove.
	// RemoveMCP ...
	//
	// Summary: Deletes RemoveMCP operation.
	//
	// Parameters:
	//   - name: string. The name parameter.
	//
	// Returns:
	//   - None.
	//
	// Errors:
	//   - None.
	//
	// Side Effects:
	//   - None.
	RemoveMCP(name string)

	// Run executes the AI tool with a specific prompt.
	//
	// Parameters:
	//   apiKey: The API key to use for authentication with the AI provider.
	//   model: The name of the model to use (e.g., "gemini-1.5-pro").
	//   prompt: The input text prompt to send to the model.
	//
	// Returns:
	//   string: The response generated by the AI tool.
	//   error: An error if the execution fails.
	// Run ...
	//
	// Summary: Executes Run operation.
	//
	// Parameters:
	//   - apiKey: apiKey. The apiKey parameter.
	//   - model: model. The model parameter.
	//   - prompt: string. A string value.
	//
	// Returns:
	//   - string: The resulting string.
	//   - error: An error if the operation fails.
	//
	// Errors:
	//   - Returns error if the operation fails or is invalid.
	//
	// Side Effects:
	//   - None.
	Run(apiKey, model, prompt string) (string, error)
}
