load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "client_lib",
    srcs = ["main.go"],
    importpath = "github.com/mcpany/core/server/examples/upstream_service_demo/websocket/client",
    visibility = ["//visibility:private"],
    deps = ["@com_github_gorilla_websocket//:go_default_library"],
)

go_binary(
    name = "client",
    embed = [":client_lib"],
    visibility = ["//visibility:public"],
)
