# Copyright 2026 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "cmd_lib",
    srcs = ["main.go"],
    importpath = "github.com/mcpany/core/k8s/operator/cmd",
    visibility = ["//visibility:private"],
    deps = [
        "//k8s/operator/api/v1alpha1",
        "//k8s/operator/controllers",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/util/runtime",
        "@io_k8s_client_go/kubernetes/scheme",
        "@io_k8s_client_go/plugin/pkg/client/auth",
        "@io_k8s_sigs_controller_runtime//pkg/healthz",
        "@io_k8s_sigs_controller_runtime//pkg/log/zap",
        "@io_k8s_sigs_controller_runtime//pkg/metrics/server",
        "@io_k8s_sigs_controller_runtime:controller-runtime",
    ],
)

go_binary(
    name = "operator",
    embed = [":cmd_lib"],
    visibility = ["//visibility:public"],
)
