load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "client_lib",
    srcs = ["main.go"],
    importpath = "github.com/mcpany/core/server/examples/upstream_service_demo/grpc/client",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_mcpany_core//upstream_service/grpc/greeter_server/proto",
        "@org_golang_google_grpc//:grpc",
    ],
)

go_binary(
    name = "client",
    embed = [":client_lib"],
    visibility = ["//visibility:public"],
)
