# Copyright 2026 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "public_api_test",
    srcs = ["policy_test.go"],
    data = [
        "//server/cmd/mock_mcp_server",
        "//server/cmd/server",
    ],
    tags = ["integration"],
    deps = [
        "//server/tests/integration",
        "@com_github_modelcontextprotocol_go_sdk//mcp:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
    ],
)
