# Copyright 2026 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

# CircleCI Configuration
version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/go:1.24
    resource_class: medium

jobs:
  bazel-test:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Install Bazelisk
          command: |
            curl -fsSL https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o /tmp/bazelisk
            chmod +x /tmp/bazelisk
            sudo mv /tmp/bazelisk /usr/local/bin/bazelisk
      - run:
          name: Run Tests
          command: bazelisk test //...

workflows:
  version: 2
  ci:
    jobs:
      - bazel-test
