global_settings:
  bind_address: "0.0.0.0:8080"
upstream_services:
- name: echo-service
  websocket_service:
    address: "ws://localhost:8082/echo"
    calls:
    - operation_id: "echo"
      description: "Echoes a message back."