load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "my-tool_lib",
    srcs = ["main.go"],
    importpath = "github.com/mcpany/core/server/examples/demo/stdio/my-tool",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "my-tool",
    embed = [":my-tool_lib"],
    visibility = ["//visibility:public"],
)
