/**
 * Copyright 2026 Author(s) of MCP Any
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Severity levels for alerts.
 * - critical: Immediate action required.
 * - warning: Attention required, but not immediately critical.
 * - info: Informational message.
 */
export type Severity = "critical" | "warning" | "info";

/**
 * AlertStatus type definition.
 */
export type AlertStatus = "active" | "acknowledged" | "resolved";

/**
 * Alert type definition.
 */
export interface Alert {
  id: string;
  title: string;
  message: string;
  severity: Severity;
  status: AlertStatus;
  service: string;
  timestamp: string; // ISO string
  source: string;
}

/**
 * AlertRule defines a rule for triggering alerts based on service conditions.
 */
export interface AlertRule {
  /** The unique identifier for the alert rule. */
  id: string;
  /** The human-readable name of the rule. */
  name: string;
  /** The condition expression that triggers the alert. */
  condition: string;
  /** The severity level of the alert generated by this rule. */
  severity: Severity;
  /** The ID of the service this rule applies to. */
  service: string;
  /** Whether the rule is currently enabled. */
  enabled: boolean;
}
