// Copyright 2025 Author(s) of MCP Any
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: greeter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
// HelloRequest represents a request containing a name.
//
// Summary: Represents a Hello Request.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset clears the message.
//
// Summary: Clears the message.
//
// Parameters:
//   - None.
//
// Returns:
//   - None.
//
// Errors:
//   - None.
//
// Side Effects:
//   - Modifies the receiver.
func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String returns a string representation.
//
// Summary: Returns a string representation.
//
// Parameters:
//   - None.
//
// Returns:
//   - string: The string representation.
//
// Errors:
//   - None.
//
// Side Effects:
//   - None.
func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage marks this as a proto message.
//
// Summary: Marks as proto message.
//
// Parameters:
//   - None.
//
// Returns:
//   - None.
//
// Errors:
//   - None.
//
// Side Effects:
//   - None.
func (*HelloRequest) ProtoMessage() {}

// ProtoReflect returns reflection information.
//
// Summary: Returns reflection information.
//
// Parameters:
//   - None.
//
// Returns:
//   - protoreflect.Message: The reflection message.
//
// Errors:
//   - None.
//
// Side Effects:
//   - None.
func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
// Descriptor gets the protobuf message descriptor.
//
// Summary: Gets the protobuf message descriptor.
//
// Parameters:
//   - None.
//
// Returns:
//   - []byte: The raw descriptor.
//   - []int: The descriptor index.
//
// Errors:
//   - None.
//
// Side Effects:
//   - None.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{0}
}

// GetName gets the name.
//
// Summary: Gets the name.
//
// Parameters:
//   - None.
//
// Returns:
//   - string: The name.
//
// Errors:
//   - None.
//
// Side Effects:
//   - None.
func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
// HelloReply represents a response containing a greeting message.
//
// Summary: Represents a Hello Reply.
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Reset clears the message.
//
// Summary: Clears the message.
//
// Parameters:
//   - None.
//
// Returns:
//   - None.
//
// Errors:
//   - None.
//
// Side Effects:
//   - Modifies the receiver.
func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

// String returns a string representation.
//
// Summary: Returns a string representation.
//
// Parameters:
//   - None.
//
// Returns:
//   - string: The string representation.
//
// Errors:
//   - None.
//
// Side Effects:
//   - None.
func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage marks this as a proto message.
//
// Summary: Marks as proto message.
//
// Parameters:
//   - None.
//
// Returns:
//   - None.
//
// Errors:
//   - None.
//
// Side Effects:
//   - None.
func (*HelloReply) ProtoMessage() {}

// ProtoReflect returns reflection information.
//
// Summary: Returns reflection information.
//
// Parameters:
//   - None.
//
// Returns:
//   - protoreflect.Message: The reflection message.
//
// Errors:
//   - None.
//
// Side Effects:
//   - None.
func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
// Descriptor gets the protobuf message descriptor.
//
// Summary: Gets the protobuf message descriptor.
//
// Parameters:
//   - None.
//
// Returns:
//   - []byte: The raw descriptor.
//   - []int: The descriptor index.
//
// Errors:
//   - None.
//
// Side Effects:
//   - None.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_greeter_proto_rawDescGZIP(), []int{1}
}

// GetMessage gets the message.
//
// Summary: Gets the message.
//
// Parameters:
//   - None.
//
// Returns:
//   - string: The message.
//
// Errors:
//   - None.
//
// Side Effects:
//   - None.
func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// File_greeter_proto is the proto reflection file descriptor.
//
// Summary: Proto reflection file descriptor.
var File_greeter_proto protoreflect.FileDescriptor

const file_greeter_proto_rawDesc = "" +
	"\n" +
	"\rgreeter.proto\x12\agreeter\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2C\n" +
	"\aGreeter\x128\n" +
	"\bSayHello\x12\x15.greeter.HelloRequest\x1a\x13.greeter.HelloReply\"\x00BCZAgithub.com/mcpany/core/upstream_service/grpc/greeter_server/protob\x06proto3"

var (
	file_greeter_proto_rawDescOnce sync.Once
	file_greeter_proto_rawDescData []byte
)

func file_greeter_proto_rawDescGZIP() []byte {
	file_greeter_proto_rawDescOnce.Do(func() {
		file_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greeter_proto_rawDesc), len(file_greeter_proto_rawDesc)))
	})
	return file_greeter_proto_rawDescData
}

var file_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_greeter_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: greeter.HelloRequest
	(*HelloReply)(nil),   // 1: greeter.HelloReply
}
var file_greeter_proto_depIdxs = []int32{
	0, // 0: greeter.Greeter.SayHello:input_type -> greeter.HelloRequest
	1, // 1: greeter.Greeter.SayHello:output_type -> greeter.HelloReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_greeter_proto_init() }
func file_greeter_proto_init() {
	if File_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greeter_proto_rawDesc), len(file_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greeter_proto_goTypes,
		DependencyIndexes: file_greeter_proto_depIdxs,
		MessageInfos:      file_greeter_proto_msgTypes,
	}.Build()
	File_greeter_proto = out.File
	file_greeter_proto_goTypes = nil
	file_greeter_proto_depIdxs = nil
}
