# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

version: "2"

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - build
    - vendor

linters:
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - govet
    - nolintlint
    - prealloc
    - revive
    - gosec
    - staticcheck
    - tparallel
    - unconvert
    - unused
    - misspell
    - whitespace
    - godot
    - unparam
    - nakedret
    - dogsled
    - asciicheck
    - makezero
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

issues:
  exclude-dirs:
    - build
    - vendor
    - .cache
  exclude-rules:
    - path: "_test.go"
      linters:
        - "errcheck"
  skip-files:
    - '.*\.pb\.go$'
    - lll
    - funlen
    - wsl
    - gci
    - gofumpt
