version: "2"

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - build
    - vendor

linters:
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - govet
    - nolintlint
    - prealloc
    #- revive
    - gosec
    - staticcheck
    - tparallel
    - unconvert
    - unused

issues:
  exclude-dirs:
    - build
    - vendor
    - .cache
  exclude-rules:
    - path: "_test.go"
      linters:
        - "errcheck"
  skip-files:
    - '.*\.pb\.go$'
