// Copyright 2025 Author(s) of MCP Any
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/config/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Where the API key is located.
type APIKeyAuth_Location int32

const (
	APIKeyAuth_HEADER APIKeyAuth_Location = 0
	APIKeyAuth_QUERY  APIKeyAuth_Location = 1
	APIKeyAuth_COOKIE APIKeyAuth_Location = 2 // Added COOKIE for completeness
)

// Enum value maps for APIKeyAuth_Location.
var (
	APIKeyAuth_Location_name = map[int32]string{
		0: "HEADER",
		1: "QUERY",
		2: "COOKIE",
	}
	APIKeyAuth_Location_value = map[string]int32{
		"HEADER": 0,
		"QUERY":  1,
		"COOKIE": 2,
	}
)

func (x APIKeyAuth_Location) Enum() *APIKeyAuth_Location {
	p := new(APIKeyAuth_Location)
	*p = x
	return p
}

func (x APIKeyAuth_Location) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (APIKeyAuth_Location) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_config_v1_auth_proto_enumTypes[0].Descriptor()
}

func (APIKeyAuth_Location) Type() protoreflect.EnumType {
	return &file_proto_config_v1_auth_proto_enumTypes[0]
}

func (x APIKeyAuth_Location) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// SecretValue represents a value that should be treated as a secret.
// It can be a plain text value, an environment variable, a file path, or content fetched from a remote URL.
type SecretValue struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value           isSecretValue_Value    `protobuf_oneof:"value"`
	xxx_hidden_ValidationRegex *string                `protobuf:"bytes,7,opt,name=validation_regex"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SecretValue) Reset() {
	*x = SecretValue{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretValue) ProtoMessage() {}

func (x *SecretValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretValue) GetPlainText() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*secretValue_PlainText); ok {
			return x.PlainText
		}
	}
	return ""
}

func (x *SecretValue) GetEnvironmentVariable() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*secretValue_EnvironmentVariable); ok {
			return x.EnvironmentVariable
		}
	}
	return ""
}

func (x *SecretValue) GetFilePath() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*secretValue_FilePath); ok {
			return x.FilePath
		}
	}
	return ""
}

func (x *SecretValue) GetRemoteContent() *RemoteContent {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*secretValue_RemoteContent); ok {
			return x.RemoteContent
		}
	}
	return nil
}

func (x *SecretValue) GetVault() *VaultSecret {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*secretValue_Vault); ok {
			return x.Vault
		}
	}
	return nil
}

func (x *SecretValue) GetAwsSecretManager() *AwsSecretManagerSecret {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*secretValue_AwsSecretManager); ok {
			return x.AwsSecretManager
		}
	}
	return nil
}

func (x *SecretValue) GetValidationRegex() string {
	if x != nil {
		if x.xxx_hidden_ValidationRegex != nil {
			return *x.xxx_hidden_ValidationRegex
		}
		return ""
	}
	return ""
}

func (x *SecretValue) SetPlainText(v string) {
	x.xxx_hidden_Value = &secretValue_PlainText{v}
}

func (x *SecretValue) SetEnvironmentVariable(v string) {
	x.xxx_hidden_Value = &secretValue_EnvironmentVariable{v}
}

func (x *SecretValue) SetFilePath(v string) {
	x.xxx_hidden_Value = &secretValue_FilePath{v}
}

func (x *SecretValue) SetRemoteContent(v *RemoteContent) {
	if v == nil {
		x.xxx_hidden_Value = nil
		return
	}
	x.xxx_hidden_Value = &secretValue_RemoteContent{v}
}

func (x *SecretValue) SetVault(v *VaultSecret) {
	if v == nil {
		x.xxx_hidden_Value = nil
		return
	}
	x.xxx_hidden_Value = &secretValue_Vault{v}
}

func (x *SecretValue) SetAwsSecretManager(v *AwsSecretManagerSecret) {
	if v == nil {
		x.xxx_hidden_Value = nil
		return
	}
	x.xxx_hidden_Value = &secretValue_AwsSecretManager{v}
}

func (x *SecretValue) SetValidationRegex(v string) {
	x.xxx_hidden_ValidationRegex = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SecretValue) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *SecretValue) HasPlainText() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*secretValue_PlainText)
	return ok
}

func (x *SecretValue) HasEnvironmentVariable() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*secretValue_EnvironmentVariable)
	return ok
}

func (x *SecretValue) HasFilePath() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*secretValue_FilePath)
	return ok
}

func (x *SecretValue) HasRemoteContent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*secretValue_RemoteContent)
	return ok
}

func (x *SecretValue) HasVault() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*secretValue_Vault)
	return ok
}

func (x *SecretValue) HasAwsSecretManager() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*secretValue_AwsSecretManager)
	return ok
}

func (x *SecretValue) HasValidationRegex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SecretValue) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *SecretValue) ClearPlainText() {
	if _, ok := x.xxx_hidden_Value.(*secretValue_PlainText); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *SecretValue) ClearEnvironmentVariable() {
	if _, ok := x.xxx_hidden_Value.(*secretValue_EnvironmentVariable); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *SecretValue) ClearFilePath() {
	if _, ok := x.xxx_hidden_Value.(*secretValue_FilePath); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *SecretValue) ClearRemoteContent() {
	if _, ok := x.xxx_hidden_Value.(*secretValue_RemoteContent); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *SecretValue) ClearVault() {
	if _, ok := x.xxx_hidden_Value.(*secretValue_Vault); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *SecretValue) ClearAwsSecretManager() {
	if _, ok := x.xxx_hidden_Value.(*secretValue_AwsSecretManager); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *SecretValue) ClearValidationRegex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ValidationRegex = nil
}

const SecretValue_Value_not_set_case case_SecretValue_Value = 0
const SecretValue_PlainText_case case_SecretValue_Value = 1
const SecretValue_EnvironmentVariable_case case_SecretValue_Value = 2
const SecretValue_FilePath_case case_SecretValue_Value = 3
const SecretValue_RemoteContent_case case_SecretValue_Value = 4
const SecretValue_Vault_case case_SecretValue_Value = 5
const SecretValue_AwsSecretManager_case case_SecretValue_Value = 6

func (x *SecretValue) WhichValue() case_SecretValue_Value {
	if x == nil {
		return SecretValue_Value_not_set_case
	}
	switch x.xxx_hidden_Value.(type) {
	case *secretValue_PlainText:
		return SecretValue_PlainText_case
	case *secretValue_EnvironmentVariable:
		return SecretValue_EnvironmentVariable_case
	case *secretValue_FilePath:
		return SecretValue_FilePath_case
	case *secretValue_RemoteContent:
		return SecretValue_RemoteContent_case
	case *secretValue_Vault:
		return SecretValue_Vault_case
	case *secretValue_AwsSecretManager:
		return SecretValue_AwsSecretManager_case
	default:
		return SecretValue_Value_not_set_case
	}
}

type SecretValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Value:
	PlainText           *string
	EnvironmentVariable *string
	FilePath            *string
	RemoteContent       *RemoteContent
	Vault               *VaultSecret
	AwsSecretManager    *AwsSecretManagerSecret
	// -- end of xxx_hidden_Value
	// Optional: A regex to validate the resolved secret value.
	ValidationRegex *string
}

func (b0 SecretValue_builder) Build() *SecretValue {
	m0 := &SecretValue{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PlainText != nil {
		x.xxx_hidden_Value = &secretValue_PlainText{*b.PlainText}
	}
	if b.EnvironmentVariable != nil {
		x.xxx_hidden_Value = &secretValue_EnvironmentVariable{*b.EnvironmentVariable}
	}
	if b.FilePath != nil {
		x.xxx_hidden_Value = &secretValue_FilePath{*b.FilePath}
	}
	if b.RemoteContent != nil {
		x.xxx_hidden_Value = &secretValue_RemoteContent{b.RemoteContent}
	}
	if b.Vault != nil {
		x.xxx_hidden_Value = &secretValue_Vault{b.Vault}
	}
	if b.AwsSecretManager != nil {
		x.xxx_hidden_Value = &secretValue_AwsSecretManager{b.AwsSecretManager}
	}
	if b.ValidationRegex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ValidationRegex = b.ValidationRegex
	}
	return m0
}

type case_SecretValue_Value protoreflect.FieldNumber

func (x case_SecretValue_Value) String() string {
	md := file_proto_config_v1_auth_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSecretValue_Value interface {
	isSecretValue_Value()
}

type secretValue_PlainText struct {
	PlainText string `protobuf:"bytes,1,opt,name=plain_text,json=plainText,oneof"`
}

type secretValue_EnvironmentVariable struct {
	EnvironmentVariable string `protobuf:"bytes,2,opt,name=environment_variable,json=environmentVariable,oneof"`
}

type secretValue_FilePath struct {
	FilePath string `protobuf:"bytes,3,opt,name=file_path,json=filePath,oneof"`
}

type secretValue_RemoteContent struct {
	RemoteContent *RemoteContent `protobuf:"bytes,4,opt,name=remote_content,json=remoteContent,oneof"`
}

type secretValue_Vault struct {
	Vault *VaultSecret `protobuf:"bytes,5,opt,name=vault,oneof"`
}

type secretValue_AwsSecretManager struct {
	AwsSecretManager *AwsSecretManagerSecret `protobuf:"bytes,6,opt,name=aws_secret_manager,json=awsSecretManager,oneof"`
}

func (*secretValue_PlainText) isSecretValue_Value() {}

func (*secretValue_EnvironmentVariable) isSecretValue_Value() {}

func (*secretValue_FilePath) isSecretValue_Value() {}

func (*secretValue_RemoteContent) isSecretValue_Value() {}

func (*secretValue_Vault) isSecretValue_Value() {}

func (*secretValue_AwsSecretManager) isSecretValue_Value() {}

// AwsSecretManagerSecret defines the parameters for fetching a secret from AWS Secrets Manager.
type AwsSecretManagerSecret struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretId     *string                `protobuf:"bytes,1,opt,name=secret_id"`
	xxx_hidden_JsonKey      *string                `protobuf:"bytes,2,opt,name=json_key"`
	xxx_hidden_VersionStage *string                `protobuf:"bytes,3,opt,name=version_stage"`
	xxx_hidden_VersionId    *string                `protobuf:"bytes,4,opt,name=version_id"`
	xxx_hidden_Region       *string                `protobuf:"bytes,5,opt,name=region"`
	xxx_hidden_Profile      *string                `protobuf:"bytes,6,opt,name=profile"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AwsSecretManagerSecret) Reset() {
	*x = AwsSecretManagerSecret{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsSecretManagerSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsSecretManagerSecret) ProtoMessage() {}

func (x *AwsSecretManagerSecret) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AwsSecretManagerSecret) GetSecretId() string {
	if x != nil {
		if x.xxx_hidden_SecretId != nil {
			return *x.xxx_hidden_SecretId
		}
		return ""
	}
	return ""
}

func (x *AwsSecretManagerSecret) GetJsonKey() string {
	if x != nil {
		if x.xxx_hidden_JsonKey != nil {
			return *x.xxx_hidden_JsonKey
		}
		return ""
	}
	return ""
}

func (x *AwsSecretManagerSecret) GetVersionStage() string {
	if x != nil {
		if x.xxx_hidden_VersionStage != nil {
			return *x.xxx_hidden_VersionStage
		}
		return ""
	}
	return ""
}

func (x *AwsSecretManagerSecret) GetVersionId() string {
	if x != nil {
		if x.xxx_hidden_VersionId != nil {
			return *x.xxx_hidden_VersionId
		}
		return ""
	}
	return ""
}

func (x *AwsSecretManagerSecret) GetRegion() string {
	if x != nil {
		if x.xxx_hidden_Region != nil {
			return *x.xxx_hidden_Region
		}
		return ""
	}
	return ""
}

func (x *AwsSecretManagerSecret) GetProfile() string {
	if x != nil {
		if x.xxx_hidden_Profile != nil {
			return *x.xxx_hidden_Profile
		}
		return ""
	}
	return ""
}

func (x *AwsSecretManagerSecret) SetSecretId(v string) {
	x.xxx_hidden_SecretId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *AwsSecretManagerSecret) SetJsonKey(v string) {
	x.xxx_hidden_JsonKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *AwsSecretManagerSecret) SetVersionStage(v string) {
	x.xxx_hidden_VersionStage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *AwsSecretManagerSecret) SetVersionId(v string) {
	x.xxx_hidden_VersionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *AwsSecretManagerSecret) SetRegion(v string) {
	x.xxx_hidden_Region = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *AwsSecretManagerSecret) SetProfile(v string) {
	x.xxx_hidden_Profile = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *AwsSecretManagerSecret) HasSecretId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AwsSecretManagerSecret) HasJsonKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AwsSecretManagerSecret) HasVersionStage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AwsSecretManagerSecret) HasVersionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AwsSecretManagerSecret) HasRegion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AwsSecretManagerSecret) HasProfile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *AwsSecretManagerSecret) ClearSecretId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SecretId = nil
}

func (x *AwsSecretManagerSecret) ClearJsonKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_JsonKey = nil
}

func (x *AwsSecretManagerSecret) ClearVersionStage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_VersionStage = nil
}

func (x *AwsSecretManagerSecret) ClearVersionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_VersionId = nil
}

func (x *AwsSecretManagerSecret) ClearRegion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Region = nil
}

func (x *AwsSecretManagerSecret) ClearProfile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Profile = nil
}

type AwsSecretManagerSecret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name or ARN of the secret.
	SecretId *string
	// Optional: The key to extract from the secret JSON.
	JsonKey *string
	// Optional: The version stage (defaults to AWSCURRENT).
	VersionStage *string
	// Optional: The version ID.
	VersionId *string
	// Optional: The region. If not set, uses environment or profile.
	Region *string
	// Optional: Profile to use.
	Profile *string
}

func (b0 AwsSecretManagerSecret_builder) Build() *AwsSecretManagerSecret {
	m0 := &AwsSecretManagerSecret{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SecretId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_SecretId = b.SecretId
	}
	if b.JsonKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_JsonKey = b.JsonKey
	}
	if b.VersionStage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_VersionStage = b.VersionStage
	}
	if b.VersionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_VersionId = b.VersionId
	}
	if b.Region != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Region = b.Region
	}
	if b.Profile != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Profile = b.Profile
	}
	return m0
}

// VaultSecret defines the parameters for fetching a secret from HashiCorp Vault.
type VaultSecret struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Address     *string                `protobuf:"bytes,1,opt,name=address"`
	xxx_hidden_Token       *SecretValue           `protobuf:"bytes,2,opt,name=token"`
	xxx_hidden_Path        *string                `protobuf:"bytes,3,opt,name=path"`
	xxx_hidden_Key         *string                `protobuf:"bytes,4,opt,name=key"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VaultSecret) Reset() {
	*x = VaultSecret{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultSecret) ProtoMessage() {}

func (x *VaultSecret) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VaultSecret) GetAddress() string {
	if x != nil {
		if x.xxx_hidden_Address != nil {
			return *x.xxx_hidden_Address
		}
		return ""
	}
	return ""
}

func (x *VaultSecret) GetToken() *SecretValue {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return nil
}

func (x *VaultSecret) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *VaultSecret) GetKey() string {
	if x != nil {
		if x.xxx_hidden_Key != nil {
			return *x.xxx_hidden_Key
		}
		return ""
	}
	return ""
}

func (x *VaultSecret) SetAddress(v string) {
	x.xxx_hidden_Address = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *VaultSecret) SetToken(v *SecretValue) {
	x.xxx_hidden_Token = v
}

func (x *VaultSecret) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *VaultSecret) SetKey(v string) {
	x.xxx_hidden_Key = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *VaultSecret) HasAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *VaultSecret) HasToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Token != nil
}

func (x *VaultSecret) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *VaultSecret) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *VaultSecret) ClearAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Address = nil
}

func (x *VaultSecret) ClearToken() {
	x.xxx_hidden_Token = nil
}

func (x *VaultSecret) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Path = nil
}

func (x *VaultSecret) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Key = nil
}

type VaultSecret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The address of the Vault server (e.g., "https://vault.example.com").
	Address *string
	// The token to authenticate with Vault.
	Token *SecretValue
	// The path to the secret in Vault (e.g., "secret/data/my-app/db").
	Path *string
	// The key of the secret to retrieve from the path.
	Key *string
}

func (b0 VaultSecret_builder) Build() *VaultSecret {
	m0 := &VaultSecret{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Address != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Address = b.Address
	}
	x.xxx_hidden_Token = b.Token
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Path = b.Path
	}
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Key = b.Key
	}
	return m0
}

// RemoteContent represents content that is fetched from a remote URL.
type RemoteContent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HttpUrl     *string                `protobuf:"bytes,1,opt,name=http_url,json=httpUrl"`
	xxx_hidden_Auth        *Authentication        `protobuf:"bytes,2,opt,name=auth"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RemoteContent) Reset() {
	*x = RemoteContent{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteContent) ProtoMessage() {}

func (x *RemoteContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RemoteContent) GetHttpUrl() string {
	if x != nil {
		if x.xxx_hidden_HttpUrl != nil {
			return *x.xxx_hidden_HttpUrl
		}
		return ""
	}
	return ""
}

func (x *RemoteContent) GetAuth() *Authentication {
	if x != nil {
		return x.xxx_hidden_Auth
	}
	return nil
}

func (x *RemoteContent) SetHttpUrl(v string) {
	x.xxx_hidden_HttpUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RemoteContent) SetAuth(v *Authentication) {
	x.xxx_hidden_Auth = v
}

func (x *RemoteContent) HasHttpUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RemoteContent) HasAuth() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Auth != nil
}

func (x *RemoteContent) ClearHttpUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_HttpUrl = nil
}

func (x *RemoteContent) ClearAuth() {
	x.xxx_hidden_Auth = nil
}

type RemoteContent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	HttpUrl *string
	Auth    *Authentication
}

func (b0 RemoteContent_builder) Build() *RemoteContent {
	m0 := &RemoteContent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HttpUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_HttpUrl = b.HttpUrl
	}
	x.xxx_hidden_Auth = b.Auth
	return m0
}

// Authentication defines an authentication method that can be used for both
// incoming requests (validation) and outgoing requests (client).
type Authentication struct {
	state                 protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_AuthMethod isAuthentication_AuthMethod `protobuf_oneof:"auth_method"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Authentication) GetApiKey() *APIKeyAuth {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthMethod.(*authentication_ApiKey); ok {
			return x.ApiKey
		}
	}
	return nil
}

func (x *Authentication) GetBearerToken() *BearerTokenAuth {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthMethod.(*authentication_BearerToken); ok {
			return x.BearerToken
		}
	}
	return nil
}

func (x *Authentication) GetBasicAuth() *BasicAuth {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthMethod.(*authentication_BasicAuth); ok {
			return x.BasicAuth
		}
	}
	return nil
}

func (x *Authentication) GetOauth2() *OAuth2Auth {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthMethod.(*authentication_Oauth2); ok {
			return x.Oauth2
		}
	}
	return nil
}

func (x *Authentication) GetOidc() *OIDCAuth {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthMethod.(*authentication_Oidc); ok {
			return x.Oidc
		}
	}
	return nil
}

func (x *Authentication) GetMtls() *MTLSAuth {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthMethod.(*authentication_Mtls); ok {
			return x.Mtls
		}
	}
	return nil
}

func (x *Authentication) GetTrustedHeader() *TrustedHeaderAuth {
	if x != nil {
		if x, ok := x.xxx_hidden_AuthMethod.(*authentication_TrustedHeader); ok {
			return x.TrustedHeader
		}
	}
	return nil
}

func (x *Authentication) SetApiKey(v *APIKeyAuth) {
	if v == nil {
		x.xxx_hidden_AuthMethod = nil
		return
	}
	x.xxx_hidden_AuthMethod = &authentication_ApiKey{v}
}

func (x *Authentication) SetBearerToken(v *BearerTokenAuth) {
	if v == nil {
		x.xxx_hidden_AuthMethod = nil
		return
	}
	x.xxx_hidden_AuthMethod = &authentication_BearerToken{v}
}

func (x *Authentication) SetBasicAuth(v *BasicAuth) {
	if v == nil {
		x.xxx_hidden_AuthMethod = nil
		return
	}
	x.xxx_hidden_AuthMethod = &authentication_BasicAuth{v}
}

func (x *Authentication) SetOauth2(v *OAuth2Auth) {
	if v == nil {
		x.xxx_hidden_AuthMethod = nil
		return
	}
	x.xxx_hidden_AuthMethod = &authentication_Oauth2{v}
}

func (x *Authentication) SetOidc(v *OIDCAuth) {
	if v == nil {
		x.xxx_hidden_AuthMethod = nil
		return
	}
	x.xxx_hidden_AuthMethod = &authentication_Oidc{v}
}

func (x *Authentication) SetMtls(v *MTLSAuth) {
	if v == nil {
		x.xxx_hidden_AuthMethod = nil
		return
	}
	x.xxx_hidden_AuthMethod = &authentication_Mtls{v}
}

func (x *Authentication) SetTrustedHeader(v *TrustedHeaderAuth) {
	if v == nil {
		x.xxx_hidden_AuthMethod = nil
		return
	}
	x.xxx_hidden_AuthMethod = &authentication_TrustedHeader{v}
}

func (x *Authentication) HasAuthMethod() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AuthMethod != nil
}

func (x *Authentication) HasApiKey() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthMethod.(*authentication_ApiKey)
	return ok
}

func (x *Authentication) HasBearerToken() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthMethod.(*authentication_BearerToken)
	return ok
}

func (x *Authentication) HasBasicAuth() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthMethod.(*authentication_BasicAuth)
	return ok
}

func (x *Authentication) HasOauth2() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthMethod.(*authentication_Oauth2)
	return ok
}

func (x *Authentication) HasOidc() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthMethod.(*authentication_Oidc)
	return ok
}

func (x *Authentication) HasMtls() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthMethod.(*authentication_Mtls)
	return ok
}

func (x *Authentication) HasTrustedHeader() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_AuthMethod.(*authentication_TrustedHeader)
	return ok
}

func (x *Authentication) ClearAuthMethod() {
	x.xxx_hidden_AuthMethod = nil
}

func (x *Authentication) ClearApiKey() {
	if _, ok := x.xxx_hidden_AuthMethod.(*authentication_ApiKey); ok {
		x.xxx_hidden_AuthMethod = nil
	}
}

func (x *Authentication) ClearBearerToken() {
	if _, ok := x.xxx_hidden_AuthMethod.(*authentication_BearerToken); ok {
		x.xxx_hidden_AuthMethod = nil
	}
}

func (x *Authentication) ClearBasicAuth() {
	if _, ok := x.xxx_hidden_AuthMethod.(*authentication_BasicAuth); ok {
		x.xxx_hidden_AuthMethod = nil
	}
}

func (x *Authentication) ClearOauth2() {
	if _, ok := x.xxx_hidden_AuthMethod.(*authentication_Oauth2); ok {
		x.xxx_hidden_AuthMethod = nil
	}
}

func (x *Authentication) ClearOidc() {
	if _, ok := x.xxx_hidden_AuthMethod.(*authentication_Oidc); ok {
		x.xxx_hidden_AuthMethod = nil
	}
}

func (x *Authentication) ClearMtls() {
	if _, ok := x.xxx_hidden_AuthMethod.(*authentication_Mtls); ok {
		x.xxx_hidden_AuthMethod = nil
	}
}

func (x *Authentication) ClearTrustedHeader() {
	if _, ok := x.xxx_hidden_AuthMethod.(*authentication_TrustedHeader); ok {
		x.xxx_hidden_AuthMethod = nil
	}
}

const Authentication_AuthMethod_not_set_case case_Authentication_AuthMethod = 0
const Authentication_ApiKey_case case_Authentication_AuthMethod = 1
const Authentication_BearerToken_case case_Authentication_AuthMethod = 2
const Authentication_BasicAuth_case case_Authentication_AuthMethod = 3
const Authentication_Oauth2_case case_Authentication_AuthMethod = 4
const Authentication_Oidc_case case_Authentication_AuthMethod = 5
const Authentication_Mtls_case case_Authentication_AuthMethod = 6
const Authentication_TrustedHeader_case case_Authentication_AuthMethod = 7

func (x *Authentication) WhichAuthMethod() case_Authentication_AuthMethod {
	if x == nil {
		return Authentication_AuthMethod_not_set_case
	}
	switch x.xxx_hidden_AuthMethod.(type) {
	case *authentication_ApiKey:
		return Authentication_ApiKey_case
	case *authentication_BearerToken:
		return Authentication_BearerToken_case
	case *authentication_BasicAuth:
		return Authentication_BasicAuth_case
	case *authentication_Oauth2:
		return Authentication_Oauth2_case
	case *authentication_Oidc:
		return Authentication_Oidc_case
	case *authentication_Mtls:
		return Authentication_Mtls_case
	case *authentication_TrustedHeader:
		return Authentication_TrustedHeader_case
	default:
		return Authentication_AuthMethod_not_set_case
	}
}

type Authentication_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_AuthMethod:
	ApiKey        *APIKeyAuth
	BearerToken   *BearerTokenAuth
	BasicAuth     *BasicAuth
	Oauth2        *OAuth2Auth
	Oidc          *OIDCAuth
	Mtls          *MTLSAuth
	TrustedHeader *TrustedHeaderAuth
	// -- end of xxx_hidden_AuthMethod
}

func (b0 Authentication_builder) Build() *Authentication {
	m0 := &Authentication{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ApiKey != nil {
		x.xxx_hidden_AuthMethod = &authentication_ApiKey{b.ApiKey}
	}
	if b.BearerToken != nil {
		x.xxx_hidden_AuthMethod = &authentication_BearerToken{b.BearerToken}
	}
	if b.BasicAuth != nil {
		x.xxx_hidden_AuthMethod = &authentication_BasicAuth{b.BasicAuth}
	}
	if b.Oauth2 != nil {
		x.xxx_hidden_AuthMethod = &authentication_Oauth2{b.Oauth2}
	}
	if b.Oidc != nil {
		x.xxx_hidden_AuthMethod = &authentication_Oidc{b.Oidc}
	}
	if b.Mtls != nil {
		x.xxx_hidden_AuthMethod = &authentication_Mtls{b.Mtls}
	}
	if b.TrustedHeader != nil {
		x.xxx_hidden_AuthMethod = &authentication_TrustedHeader{b.TrustedHeader}
	}
	return m0
}

type case_Authentication_AuthMethod protoreflect.FieldNumber

func (x case_Authentication_AuthMethod) String() string {
	md := file_proto_config_v1_auth_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAuthentication_AuthMethod interface {
	isAuthentication_AuthMethod()
}

type authentication_ApiKey struct {
	ApiKey *APIKeyAuth `protobuf:"bytes,1,opt,name=api_key,oneof"`
}

type authentication_BearerToken struct {
	BearerToken *BearerTokenAuth `protobuf:"bytes,2,opt,name=bearer_token,oneof"`
}

type authentication_BasicAuth struct {
	BasicAuth *BasicAuth `protobuf:"bytes,3,opt,name=basic_auth,oneof"`
}

type authentication_Oauth2 struct {
	Oauth2 *OAuth2Auth `protobuf:"bytes,4,opt,name=oauth2,oneof"`
}

type authentication_Oidc struct {
	Oidc *OIDCAuth `protobuf:"bytes,5,opt,name=oidc,oneof"`
}

type authentication_Mtls struct {
	Mtls *MTLSAuth `protobuf:"bytes,6,opt,name=mtls,oneof"`
}

type authentication_TrustedHeader struct {
	TrustedHeader *TrustedHeaderAuth `protobuf:"bytes,7,opt,name=trusted_header,oneof"`
}

func (*authentication_ApiKey) isAuthentication_AuthMethod() {}

func (*authentication_BearerToken) isAuthentication_AuthMethod() {}

func (*authentication_BasicAuth) isAuthentication_AuthMethod() {}

func (*authentication_Oauth2) isAuthentication_AuthMethod() {}

func (*authentication_Oidc) isAuthentication_AuthMethod() {}

func (*authentication_Mtls) isAuthentication_AuthMethod() {}

func (*authentication_TrustedHeader) isAuthentication_AuthMethod() {}

// APIKeyAuth defines authentication using an API key.
type APIKeyAuth struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ParamName         *string                `protobuf:"bytes,1,opt,name=param_name"`
	xxx_hidden_In                APIKeyAuth_Location    `protobuf:"varint,2,opt,name=in,enum=mcpany.config.v1.APIKeyAuth_Location"`
	xxx_hidden_Value             *SecretValue           `protobuf:"bytes,3,opt,name=value"`
	xxx_hidden_VerificationValue *string                `protobuf:"bytes,4,opt,name=verification_value"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *APIKeyAuth) Reset() {
	*x = APIKeyAuth{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyAuth) ProtoMessage() {}

func (x *APIKeyAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *APIKeyAuth) GetParamName() string {
	if x != nil {
		if x.xxx_hidden_ParamName != nil {
			return *x.xxx_hidden_ParamName
		}
		return ""
	}
	return ""
}

func (x *APIKeyAuth) GetIn() APIKeyAuth_Location {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_In
		}
	}
	return APIKeyAuth_HEADER
}

func (x *APIKeyAuth) GetValue() *SecretValue {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *APIKeyAuth) GetVerificationValue() string {
	if x != nil {
		if x.xxx_hidden_VerificationValue != nil {
			return *x.xxx_hidden_VerificationValue
		}
		return ""
	}
	return ""
}

func (x *APIKeyAuth) SetParamName(v string) {
	x.xxx_hidden_ParamName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *APIKeyAuth) SetIn(v APIKeyAuth_Location) {
	x.xxx_hidden_In = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *APIKeyAuth) SetValue(v *SecretValue) {
	x.xxx_hidden_Value = v
}

func (x *APIKeyAuth) SetVerificationValue(v string) {
	x.xxx_hidden_VerificationValue = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *APIKeyAuth) HasParamName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *APIKeyAuth) HasIn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *APIKeyAuth) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *APIKeyAuth) HasVerificationValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *APIKeyAuth) ClearParamName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ParamName = nil
}

func (x *APIKeyAuth) ClearIn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_In = APIKeyAuth_HEADER
}

func (x *APIKeyAuth) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *APIKeyAuth) ClearVerificationValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_VerificationValue = nil
}

type APIKeyAuth_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name of the parameter carrying the key (e.g., "X-API-Key", "api_key").
	ParamName *string
	In        *APIKeyAuth_Location
	// The API key value. Used for client authentication (outgoing).
	Value *SecretValue
	// The expected API key value. Used for server validation (incoming).
	// This is a plain string because we compare against it.
	VerificationValue *string
}

func (b0 APIKeyAuth_builder) Build() *APIKeyAuth {
	m0 := &APIKeyAuth{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ParamName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ParamName = b.ParamName
	}
	if b.In != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_In = *b.In
	}
	x.xxx_hidden_Value = b.Value
	if b.VerificationValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_VerificationValue = b.VerificationValue
	}
	return m0
}

// BearerTokenAuth defines authentication using a bearer token.
type BearerTokenAuth struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token *SecretValue           `protobuf:"bytes,1,opt,name=token"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BearerTokenAuth) Reset() {
	*x = BearerTokenAuth{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BearerTokenAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BearerTokenAuth) ProtoMessage() {}

func (x *BearerTokenAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BearerTokenAuth) GetToken() *SecretValue {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return nil
}

func (x *BearerTokenAuth) SetToken(v *SecretValue) {
	x.xxx_hidden_Token = v
}

func (x *BearerTokenAuth) HasToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Token != nil
}

func (x *BearerTokenAuth) ClearToken() {
	x.xxx_hidden_Token = nil
}

type BearerTokenAuth_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The bearer token.
	Token *SecretValue
}

func (b0 BearerTokenAuth_builder) Build() *BearerTokenAuth {
	m0 := &BearerTokenAuth{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Token = b.Token
	return m0
}

// BasicAuth defines authentication using a username and password.
type BasicAuth struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Username     *string                `protobuf:"bytes,1,opt,name=username"`
	xxx_hidden_Password     *SecretValue           `protobuf:"bytes,2,opt,name=password"`
	xxx_hidden_PasswordHash *string                `protobuf:"bytes,3,opt,name=password_hash"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *BasicAuth) Reset() {
	*x = BasicAuth{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuth) ProtoMessage() {}

func (x *BasicAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BasicAuth) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *BasicAuth) GetPassword() *SecretValue {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return nil
}

func (x *BasicAuth) GetPasswordHash() string {
	if x != nil {
		if x.xxx_hidden_PasswordHash != nil {
			return *x.xxx_hidden_PasswordHash
		}
		return ""
	}
	return ""
}

func (x *BasicAuth) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *BasicAuth) SetPassword(v *SecretValue) {
	x.xxx_hidden_Password = v
}

func (x *BasicAuth) SetPasswordHash(v string) {
	x.xxx_hidden_PasswordHash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *BasicAuth) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BasicAuth) HasPassword() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Password != nil
}

func (x *BasicAuth) HasPasswordHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *BasicAuth) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Username = nil
}

func (x *BasicAuth) ClearPassword() {
	x.xxx_hidden_Password = nil
}

func (x *BasicAuth) ClearPasswordHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_PasswordHash = nil
}

type BasicAuth_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Username *string
	// The password. Used for client authentication (outgoing).
	Password *SecretValue
	// The bcrypt hash of the password. Used for server validation (incoming).
	PasswordHash *string
}

func (b0 BasicAuth_builder) Build() *BasicAuth {
	m0 := &BasicAuth{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Username = b.Username
	}
	x.xxx_hidden_Password = b.Password
	if b.PasswordHash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_PasswordHash = b.PasswordHash
	}
	return m0
}

// OAuth2Auth defines authentication using the OAuth 2.0 client credentials flow.
type OAuth2Auth struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TokenUrl         *string                `protobuf:"bytes,1,opt,name=token_url"`
	xxx_hidden_ClientId         *SecretValue           `protobuf:"bytes,2,opt,name=client_id"`
	xxx_hidden_ClientSecret     *SecretValue           `protobuf:"bytes,3,opt,name=client_secret"`
	xxx_hidden_Scopes           *string                `protobuf:"bytes,4,opt,name=scopes"`
	xxx_hidden_IssuerUrl        *string                `protobuf:"bytes,5,opt,name=issuer_url"`
	xxx_hidden_Audience         *string                `protobuf:"bytes,6,opt,name=audience"`
	xxx_hidden_AuthorizationUrl *string                `protobuf:"bytes,7,opt,name=authorization_url"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *OAuth2Auth) Reset() {
	*x = OAuth2Auth{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2Auth) ProtoMessage() {}

func (x *OAuth2Auth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OAuth2Auth) GetTokenUrl() string {
	if x != nil {
		if x.xxx_hidden_TokenUrl != nil {
			return *x.xxx_hidden_TokenUrl
		}
		return ""
	}
	return ""
}

func (x *OAuth2Auth) GetClientId() *SecretValue {
	if x != nil {
		return x.xxx_hidden_ClientId
	}
	return nil
}

func (x *OAuth2Auth) GetClientSecret() *SecretValue {
	if x != nil {
		return x.xxx_hidden_ClientSecret
	}
	return nil
}

func (x *OAuth2Auth) GetScopes() string {
	if x != nil {
		if x.xxx_hidden_Scopes != nil {
			return *x.xxx_hidden_Scopes
		}
		return ""
	}
	return ""
}

func (x *OAuth2Auth) GetIssuerUrl() string {
	if x != nil {
		if x.xxx_hidden_IssuerUrl != nil {
			return *x.xxx_hidden_IssuerUrl
		}
		return ""
	}
	return ""
}

func (x *OAuth2Auth) GetAudience() string {
	if x != nil {
		if x.xxx_hidden_Audience != nil {
			return *x.xxx_hidden_Audience
		}
		return ""
	}
	return ""
}

func (x *OAuth2Auth) GetAuthorizationUrl() string {
	if x != nil {
		if x.xxx_hidden_AuthorizationUrl != nil {
			return *x.xxx_hidden_AuthorizationUrl
		}
		return ""
	}
	return ""
}

func (x *OAuth2Auth) SetTokenUrl(v string) {
	x.xxx_hidden_TokenUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *OAuth2Auth) SetClientId(v *SecretValue) {
	x.xxx_hidden_ClientId = v
}

func (x *OAuth2Auth) SetClientSecret(v *SecretValue) {
	x.xxx_hidden_ClientSecret = v
}

func (x *OAuth2Auth) SetScopes(v string) {
	x.xxx_hidden_Scopes = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *OAuth2Auth) SetIssuerUrl(v string) {
	x.xxx_hidden_IssuerUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *OAuth2Auth) SetAudience(v string) {
	x.xxx_hidden_Audience = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *OAuth2Auth) SetAuthorizationUrl(v string) {
	x.xxx_hidden_AuthorizationUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *OAuth2Auth) HasTokenUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OAuth2Auth) HasClientId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ClientId != nil
}

func (x *OAuth2Auth) HasClientSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ClientSecret != nil
}

func (x *OAuth2Auth) HasScopes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *OAuth2Auth) HasIssuerUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *OAuth2Auth) HasAudience() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *OAuth2Auth) HasAuthorizationUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *OAuth2Auth) ClearTokenUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TokenUrl = nil
}

func (x *OAuth2Auth) ClearClientId() {
	x.xxx_hidden_ClientId = nil
}

func (x *OAuth2Auth) ClearClientSecret() {
	x.xxx_hidden_ClientSecret = nil
}

func (x *OAuth2Auth) ClearScopes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Scopes = nil
}

func (x *OAuth2Auth) ClearIssuerUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_IssuerUrl = nil
}

func (x *OAuth2Auth) ClearAudience() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Audience = nil
}

func (x *OAuth2Auth) ClearAuthorizationUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_AuthorizationUrl = nil
}

type OAuth2Auth_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TokenUrl     *string
	ClientId     *SecretValue
	ClientSecret *SecretValue
	// Space-delimited list of scopes.
	Scopes *string
	// Issuer URL for validation/discovery.
	IssuerUrl *string
	// Audience for validation.
	Audience *string
	// Authorization URL (optional, mainly for 3-legged flows if we ever support them).
	AuthorizationUrl *string
}

func (b0 OAuth2Auth_builder) Build() *OAuth2Auth {
	m0 := &OAuth2Auth{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TokenUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_TokenUrl = b.TokenUrl
	}
	x.xxx_hidden_ClientId = b.ClientId
	x.xxx_hidden_ClientSecret = b.ClientSecret
	if b.Scopes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Scopes = b.Scopes
	}
	if b.IssuerUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_IssuerUrl = b.IssuerUrl
	}
	if b.Audience != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_Audience = b.Audience
	}
	if b.AuthorizationUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_AuthorizationUrl = b.AuthorizationUrl
	}
	return m0
}

// OIDCAuth defines authentication using OpenID Connect.
type OIDCAuth struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Issuer      *string                `protobuf:"bytes,1,opt,name=issuer"`
	xxx_hidden_Subject     *string                `protobuf:"bytes,2,opt,name=subject"`
	xxx_hidden_Email       *string                `protobuf:"bytes,3,opt,name=email"`
	xxx_hidden_Audience    []string               `protobuf:"bytes,4,rep,name=audience"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OIDCAuth) Reset() {
	*x = OIDCAuth{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDCAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCAuth) ProtoMessage() {}

func (x *OIDCAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OIDCAuth) GetIssuer() string {
	if x != nil {
		if x.xxx_hidden_Issuer != nil {
			return *x.xxx_hidden_Issuer
		}
		return ""
	}
	return ""
}

func (x *OIDCAuth) GetSubject() string {
	if x != nil {
		if x.xxx_hidden_Subject != nil {
			return *x.xxx_hidden_Subject
		}
		return ""
	}
	return ""
}

func (x *OIDCAuth) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *OIDCAuth) GetAudience() []string {
	if x != nil {
		return x.xxx_hidden_Audience
	}
	return nil
}

func (x *OIDCAuth) SetIssuer(v string) {
	x.xxx_hidden_Issuer = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *OIDCAuth) SetSubject(v string) {
	x.xxx_hidden_Subject = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *OIDCAuth) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *OIDCAuth) SetAudience(v []string) {
	x.xxx_hidden_Audience = v
}

func (x *OIDCAuth) HasIssuer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OIDCAuth) HasSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OIDCAuth) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OIDCAuth) ClearIssuer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Issuer = nil
}

func (x *OIDCAuth) ClearSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Subject = nil
}

func (x *OIDCAuth) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Email = nil
}

type OIDCAuth_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The issuer URL.
	Issuer *string
	// The subject to validate (incoming).
	Subject *string
	// The email to validate (incoming).
	Email *string
	// The audience(s) to validate (incoming).
	Audience []string
}

func (b0 OIDCAuth_builder) Build() *OIDCAuth {
	m0 := &OIDCAuth{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Issuer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Issuer = b.Issuer
	}
	if b.Subject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Subject = b.Subject
	}
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Email = b.Email
	}
	x.xxx_hidden_Audience = b.Audience
	return m0
}

// MTLSAuth defines authentication using mutual TLS.
type MTLSAuth struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClientCertPath *string                `protobuf:"bytes,1,opt,name=client_cert_path"`
	xxx_hidden_ClientKeyPath  *string                `protobuf:"bytes,2,opt,name=client_key_path"`
	xxx_hidden_CaCertPath     *string                `protobuf:"bytes,3,opt,name=ca_cert_path"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MTLSAuth) Reset() {
	*x = MTLSAuth{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MTLSAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTLSAuth) ProtoMessage() {}

func (x *MTLSAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MTLSAuth) GetClientCertPath() string {
	if x != nil {
		if x.xxx_hidden_ClientCertPath != nil {
			return *x.xxx_hidden_ClientCertPath
		}
		return ""
	}
	return ""
}

func (x *MTLSAuth) GetClientKeyPath() string {
	if x != nil {
		if x.xxx_hidden_ClientKeyPath != nil {
			return *x.xxx_hidden_ClientKeyPath
		}
		return ""
	}
	return ""
}

func (x *MTLSAuth) GetCaCertPath() string {
	if x != nil {
		if x.xxx_hidden_CaCertPath != nil {
			return *x.xxx_hidden_CaCertPath
		}
		return ""
	}
	return ""
}

func (x *MTLSAuth) SetClientCertPath(v string) {
	x.xxx_hidden_ClientCertPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *MTLSAuth) SetClientKeyPath(v string) {
	x.xxx_hidden_ClientKeyPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *MTLSAuth) SetCaCertPath(v string) {
	x.xxx_hidden_CaCertPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *MTLSAuth) HasClientCertPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MTLSAuth) HasClientKeyPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MTLSAuth) HasCaCertPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MTLSAuth) ClearClientCertPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ClientCertPath = nil
}

func (x *MTLSAuth) ClearClientKeyPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClientKeyPath = nil
}

func (x *MTLSAuth) ClearCaCertPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CaCertPath = nil
}

type MTLSAuth_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Path to the client certificate file.
	ClientCertPath *string
	// Path to the client private key file.
	ClientKeyPath *string
	// Path to the CA certificate file for verifying the server's certificate.
	CaCertPath *string
}

func (b0 MTLSAuth_builder) Build() *MTLSAuth {
	m0 := &MTLSAuth{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ClientCertPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_ClientCertPath = b.ClientCertPath
	}
	if b.ClientKeyPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ClientKeyPath = b.ClientKeyPath
	}
	if b.CaCertPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_CaCertPath = b.CaCertPath
	}
	return m0
}

// TrustedHeaderAuth defines authentication using a trusted header.
type TrustedHeaderAuth struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HeaderName  *string                `protobuf:"bytes,1,opt,name=header_name"`
	xxx_hidden_HeaderValue *string                `protobuf:"bytes,2,opt,name=header_value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TrustedHeaderAuth) Reset() {
	*x = TrustedHeaderAuth{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustedHeaderAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustedHeaderAuth) ProtoMessage() {}

func (x *TrustedHeaderAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TrustedHeaderAuth) GetHeaderName() string {
	if x != nil {
		if x.xxx_hidden_HeaderName != nil {
			return *x.xxx_hidden_HeaderName
		}
		return ""
	}
	return ""
}

func (x *TrustedHeaderAuth) GetHeaderValue() string {
	if x != nil {
		if x.xxx_hidden_HeaderValue != nil {
			return *x.xxx_hidden_HeaderValue
		}
		return ""
	}
	return ""
}

func (x *TrustedHeaderAuth) SetHeaderName(v string) {
	x.xxx_hidden_HeaderName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *TrustedHeaderAuth) SetHeaderValue(v string) {
	x.xxx_hidden_HeaderValue = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *TrustedHeaderAuth) HasHeaderName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TrustedHeaderAuth) HasHeaderValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TrustedHeaderAuth) ClearHeaderName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_HeaderName = nil
}

func (x *TrustedHeaderAuth) ClearHeaderValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_HeaderValue = nil
}

type TrustedHeaderAuth_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	HeaderName  *string
	HeaderValue *string
}

func (b0 TrustedHeaderAuth_builder) Build() *TrustedHeaderAuth {
	m0 := &TrustedHeaderAuth{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HeaderName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_HeaderName = b.HeaderName
	}
	if b.HeaderValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_HeaderValue = b.HeaderValue
	}
	return m0
}

// UserToken represents an OAuth2 token stored for a user.
type UserToken struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId       *string                `protobuf:"bytes,1,opt,name=user_id"`
	xxx_hidden_ServiceId    *string                `protobuf:"bytes,2,opt,name=service_id"`
	xxx_hidden_AccessToken  *string                `protobuf:"bytes,3,opt,name=access_token"`
	xxx_hidden_RefreshToken *string                `protobuf:"bytes,4,opt,name=refresh_token"`
	xxx_hidden_TokenType    *string                `protobuf:"bytes,5,opt,name=token_type"`
	xxx_hidden_Expiry       *string                `protobuf:"bytes,6,opt,name=expiry"`
	xxx_hidden_Scope        *string                `protobuf:"bytes,7,opt,name=scope"`
	xxx_hidden_UpdatedAt    *string                `protobuf:"bytes,8,opt,name=updated_at"`
	xxx_hidden_Email        *string                `protobuf:"bytes,9,opt,name=email"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UserToken) Reset() {
	*x = UserToken{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserToken) ProtoMessage() {}

func (x *UserToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserToken) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *UserToken) GetServiceId() string {
	if x != nil {
		if x.xxx_hidden_ServiceId != nil {
			return *x.xxx_hidden_ServiceId
		}
		return ""
	}
	return ""
}

func (x *UserToken) GetAccessToken() string {
	if x != nil {
		if x.xxx_hidden_AccessToken != nil {
			return *x.xxx_hidden_AccessToken
		}
		return ""
	}
	return ""
}

func (x *UserToken) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *UserToken) GetTokenType() string {
	if x != nil {
		if x.xxx_hidden_TokenType != nil {
			return *x.xxx_hidden_TokenType
		}
		return ""
	}
	return ""
}

func (x *UserToken) GetExpiry() string {
	if x != nil {
		if x.xxx_hidden_Expiry != nil {
			return *x.xxx_hidden_Expiry
		}
		return ""
	}
	return ""
}

func (x *UserToken) GetScope() string {
	if x != nil {
		if x.xxx_hidden_Scope != nil {
			return *x.xxx_hidden_Scope
		}
		return ""
	}
	return ""
}

func (x *UserToken) GetUpdatedAt() string {
	if x != nil {
		if x.xxx_hidden_UpdatedAt != nil {
			return *x.xxx_hidden_UpdatedAt
		}
		return ""
	}
	return ""
}

func (x *UserToken) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *UserToken) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *UserToken) SetServiceId(v string) {
	x.xxx_hidden_ServiceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *UserToken) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *UserToken) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *UserToken) SetTokenType(v string) {
	x.xxx_hidden_TokenType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *UserToken) SetExpiry(v string) {
	x.xxx_hidden_Expiry = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *UserToken) SetScope(v string) {
	x.xxx_hidden_Scope = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *UserToken) SetUpdatedAt(v string) {
	x.xxx_hidden_UpdatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *UserToken) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *UserToken) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserToken) HasServiceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserToken) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UserToken) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UserToken) HasTokenType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UserToken) HasExpiry() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UserToken) HasScope() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *UserToken) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *UserToken) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *UserToken) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_UserId = nil
}

func (x *UserToken) ClearServiceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ServiceId = nil
}

func (x *UserToken) ClearAccessToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_AccessToken = nil
}

func (x *UserToken) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_RefreshToken = nil
}

func (x *UserToken) ClearTokenType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_TokenType = nil
}

func (x *UserToken) ClearExpiry() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Expiry = nil
}

func (x *UserToken) ClearScope() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Scope = nil
}

func (x *UserToken) ClearUpdatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_UpdatedAt = nil
}

func (x *UserToken) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Email = nil
}

type UserToken_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the user who owns this token.
	UserId *string
	// The ID of the service this token is for.
	ServiceId *string
	// The access token.
	AccessToken *string
	// The refresh token.
	RefreshToken *string
	// The token type (e.g. "Bearer").
	TokenType *string
	// The expiry time of the token (RFC3339).
	Expiry *string
	// The scopes associated with the token.
	Scope *string
	// The timestamp when the token was created/updated (RFC3339).
	UpdatedAt *string
	// The email associated with the token (if available).
	Email *string
}

func (b0 UserToken_builder) Build() *UserToken {
	m0 := &UserToken{}
	b, x := &b0, m0
	_, _ = b, x
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_UserId = b.UserId
	}
	if b.ServiceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_ServiceId = b.ServiceId
	}
	if b.AccessToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_AccessToken = b.AccessToken
	}
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	if b.TokenType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_TokenType = b.TokenType
	}
	if b.Expiry != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Expiry = b.Expiry
	}
	if b.Scope != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_Scope = b.Scope
	}
	if b.UpdatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_UpdatedAt = b.UpdatedAt
	}
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_Email = b.Email
	}
	return m0
}

// Credential represents a reusable authentication configuration.
type Credential struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name           *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Authentication *Authentication        `protobuf:"bytes,3,opt,name=authentication"`
	xxx_hidden_Token          *UserToken             `protobuf:"bytes,4,opt,name=token"`
	xxx_hidden_OwnerId        *string                `protobuf:"bytes,5,opt,name=owner_id"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_proto_config_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Credential) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Credential) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Credential) GetAuthentication() *Authentication {
	if x != nil {
		return x.xxx_hidden_Authentication
	}
	return nil
}

func (x *Credential) GetToken() *UserToken {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return nil
}

func (x *Credential) GetOwnerId() string {
	if x != nil {
		if x.xxx_hidden_OwnerId != nil {
			return *x.xxx_hidden_OwnerId
		}
		return ""
	}
	return ""
}

func (x *Credential) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Credential) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Credential) SetAuthentication(v *Authentication) {
	x.xxx_hidden_Authentication = v
}

func (x *Credential) SetToken(v *UserToken) {
	x.xxx_hidden_Token = v
}

func (x *Credential) SetOwnerId(v string) {
	x.xxx_hidden_OwnerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Credential) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Credential) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Credential) HasAuthentication() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Authentication != nil
}

func (x *Credential) HasToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Token != nil
}

func (x *Credential) HasOwnerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Credential) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Credential) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Credential) ClearAuthentication() {
	x.xxx_hidden_Authentication = nil
}

func (x *Credential) ClearToken() {
	x.xxx_hidden_Token = nil
}

func (x *Credential) ClearOwnerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_OwnerId = nil
}

type Credential_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier for the credential.
	Id *string
	// Human-readable name (e.g. "My GitHub Personal").
	Name *string
	// The authentication configuration.
	Authentication *Authentication
	// Optional: For interactive OAuth, the persisted session/tokens.
	// This allows the proxy to use this credential by refreshing the token.
	Token *UserToken
	// The ID of the user who owns this credential.
	OwnerId *string
}

func (b0 Credential_builder) Build() *Credential {
	m0 := &Credential{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Authentication = b.Authentication
	x.xxx_hidden_Token = b.Token
	if b.OwnerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_OwnerId = b.OwnerId
	}
	return m0
}

var File_proto_config_v1_auth_proto protoreflect.FileDescriptor

const file_proto_config_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/config/v1/auth.proto\x12\x10mcpany.config.v1\x1a!google/protobuf/go_features.proto\"\x92\x03\n" +
	"\vSecretValue\x12\x1f\n" +
	"\n" +
	"plain_text\x18\x01 \x01(\tH\x00R\tplainText\x123\n" +
	"\x14environment_variable\x18\x02 \x01(\tH\x00R\x13environmentVariable\x12\x1d\n" +
	"\tfile_path\x18\x03 \x01(\tH\x00R\bfilePath\x12H\n" +
	"\x0eremote_content\x18\x04 \x01(\v2\x1f.mcpany.config.v1.RemoteContentH\x00R\rremoteContent\x125\n" +
	"\x05vault\x18\x05 \x01(\v2\x1d.mcpany.config.v1.VaultSecretH\x00R\x05vault\x12X\n" +
	"\x12aws_secret_manager\x18\x06 \x01(\v2(.mcpany.config.v1.AwsSecretManagerSecretH\x00R\x10awsSecretManager\x12*\n" +
	"\x10validation_regex\x18\a \x01(\tR\x10validation_regexB\a\n" +
	"\x05value\"\xca\x01\n" +
	"\x16AwsSecretManagerSecret\x12\x1c\n" +
	"\tsecret_id\x18\x01 \x01(\tR\tsecret_id\x12\x1a\n" +
	"\bjson_key\x18\x02 \x01(\tR\bjson_key\x12$\n" +
	"\rversion_stage\x18\x03 \x01(\tR\rversion_stage\x12\x1e\n" +
	"\n" +
	"version_id\x18\x04 \x01(\tR\n" +
	"version_id\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x18\n" +
	"\aprofile\x18\x06 \x01(\tR\aprofile\"\x82\x01\n" +
	"\vVaultSecret\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x123\n" +
	"\x05token\x18\x02 \x01(\v2\x1d.mcpany.config.v1.SecretValueR\x05token\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\"`\n" +
	"\rRemoteContent\x12\x19\n" +
	"\bhttp_url\x18\x01 \x01(\tR\ahttpUrl\x124\n" +
	"\x04auth\x18\x02 \x01(\v2 .mcpany.config.v1.AuthenticationR\x04auth\"\xcc\x03\n" +
	"\x0eAuthentication\x128\n" +
	"\aapi_key\x18\x01 \x01(\v2\x1c.mcpany.config.v1.APIKeyAuthH\x00R\aapi_key\x12G\n" +
	"\fbearer_token\x18\x02 \x01(\v2!.mcpany.config.v1.BearerTokenAuthH\x00R\fbearer_token\x12=\n" +
	"\n" +
	"basic_auth\x18\x03 \x01(\v2\x1b.mcpany.config.v1.BasicAuthH\x00R\n" +
	"basic_auth\x126\n" +
	"\x06oauth2\x18\x04 \x01(\v2\x1c.mcpany.config.v1.OAuth2AuthH\x00R\x06oauth2\x120\n" +
	"\x04oidc\x18\x05 \x01(\v2\x1a.mcpany.config.v1.OIDCAuthH\x00R\x04oidc\x120\n" +
	"\x04mtls\x18\x06 \x01(\v2\x1a.mcpany.config.v1.MTLSAuthH\x00R\x04mtls\x12M\n" +
	"\x0etrusted_header\x18\a \x01(\v2#.mcpany.config.v1.TrustedHeaderAuthH\x00R\x0etrusted_headerB\r\n" +
	"\vauth_method\"\xf7\x01\n" +
	"\n" +
	"APIKeyAuth\x12\x1e\n" +
	"\n" +
	"param_name\x18\x01 \x01(\tR\n" +
	"param_name\x125\n" +
	"\x02in\x18\x02 \x01(\x0e2%.mcpany.config.v1.APIKeyAuth.LocationR\x02in\x123\n" +
	"\x05value\x18\x03 \x01(\v2\x1d.mcpany.config.v1.SecretValueR\x05value\x12.\n" +
	"\x12verification_value\x18\x04 \x01(\tR\x12verification_value\"-\n" +
	"\bLocation\x12\n" +
	"\n" +
	"\x06HEADER\x10\x00\x12\t\n" +
	"\x05QUERY\x10\x01\x12\n" +
	"\n" +
	"\x06COOKIE\x10\x02\"F\n" +
	"\x0fBearerTokenAuth\x123\n" +
	"\x05token\x18\x01 \x01(\v2\x1d.mcpany.config.v1.SecretValueR\x05token\"\x88\x01\n" +
	"\tBasicAuth\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x129\n" +
	"\bpassword\x18\x02 \x01(\v2\x1d.mcpany.config.v1.SecretValueR\bpassword\x12$\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\rpassword_hash\"\xae\x02\n" +
	"\n" +
	"OAuth2Auth\x12\x1c\n" +
	"\ttoken_url\x18\x01 \x01(\tR\ttoken_url\x12;\n" +
	"\tclient_id\x18\x02 \x01(\v2\x1d.mcpany.config.v1.SecretValueR\tclient_id\x12C\n" +
	"\rclient_secret\x18\x03 \x01(\v2\x1d.mcpany.config.v1.SecretValueR\rclient_secret\x12\x16\n" +
	"\x06scopes\x18\x04 \x01(\tR\x06scopes\x12\x1e\n" +
	"\n" +
	"issuer_url\x18\x05 \x01(\tR\n" +
	"issuer_url\x12\x1a\n" +
	"\baudience\x18\x06 \x01(\tR\baudience\x12,\n" +
	"\x11authorization_url\x18\a \x01(\tR\x11authorization_url\"n\n" +
	"\bOIDCAuth\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\baudience\x18\x04 \x03(\tR\baudience\"\x84\x01\n" +
	"\bMTLSAuth\x12*\n" +
	"\x10client_cert_path\x18\x01 \x01(\tR\x10client_cert_path\x12(\n" +
	"\x0fclient_key_path\x18\x02 \x01(\tR\x0fclient_key_path\x12\"\n" +
	"\fca_cert_path\x18\x03 \x01(\tR\fca_cert_path\"Y\n" +
	"\x11TrustedHeaderAuth\x12 \n" +
	"\vheader_name\x18\x01 \x01(\tR\vheader_name\x12\"\n" +
	"\fheader_value\x18\x02 \x01(\tR\fheader_value\"\x93\x02\n" +
	"\tUserToken\x12\x18\n" +
	"\auser_id\x18\x01 \x01(\tR\auser_id\x12\x1e\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\n" +
	"service_id\x12\"\n" +
	"\faccess_token\x18\x03 \x01(\tR\faccess_token\x12$\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\rrefresh_token\x12\x1e\n" +
	"\n" +
	"token_type\x18\x05 \x01(\tR\n" +
	"token_type\x12\x16\n" +
	"\x06expiry\x18\x06 \x01(\tR\x06expiry\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scope\x12\x1e\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\n" +
	"updated_at\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\"\xc9\x01\n" +
	"\n" +
	"Credential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12H\n" +
	"\x0eauthentication\x18\x03 \x01(\v2 .mcpany.config.v1.AuthenticationR\x0eauthentication\x121\n" +
	"\x05token\x18\x04 \x01(\v2\x1b.mcpany.config.v1.UserTokenR\x05token\x12\x1a\n" +
	"\bowner_id\x18\x05 \x01(\tR\bowner_idB;B\tAuthProtoZ&github.com/mcpany/core/proto/config/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_proto_config_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_config_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_config_v1_auth_proto_goTypes = []any{
	(APIKeyAuth_Location)(0),       // 0: mcpany.config.v1.APIKeyAuth.Location
	(*SecretValue)(nil),            // 1: mcpany.config.v1.SecretValue
	(*AwsSecretManagerSecret)(nil), // 2: mcpany.config.v1.AwsSecretManagerSecret
	(*VaultSecret)(nil),            // 3: mcpany.config.v1.VaultSecret
	(*RemoteContent)(nil),          // 4: mcpany.config.v1.RemoteContent
	(*Authentication)(nil),         // 5: mcpany.config.v1.Authentication
	(*APIKeyAuth)(nil),             // 6: mcpany.config.v1.APIKeyAuth
	(*BearerTokenAuth)(nil),        // 7: mcpany.config.v1.BearerTokenAuth
	(*BasicAuth)(nil),              // 8: mcpany.config.v1.BasicAuth
	(*OAuth2Auth)(nil),             // 9: mcpany.config.v1.OAuth2Auth
	(*OIDCAuth)(nil),               // 10: mcpany.config.v1.OIDCAuth
	(*MTLSAuth)(nil),               // 11: mcpany.config.v1.MTLSAuth
	(*TrustedHeaderAuth)(nil),      // 12: mcpany.config.v1.TrustedHeaderAuth
	(*UserToken)(nil),              // 13: mcpany.config.v1.UserToken
	(*Credential)(nil),             // 14: mcpany.config.v1.Credential
}
var file_proto_config_v1_auth_proto_depIdxs = []int32{
	4,  // 0: mcpany.config.v1.SecretValue.remote_content:type_name -> mcpany.config.v1.RemoteContent
	3,  // 1: mcpany.config.v1.SecretValue.vault:type_name -> mcpany.config.v1.VaultSecret
	2,  // 2: mcpany.config.v1.SecretValue.aws_secret_manager:type_name -> mcpany.config.v1.AwsSecretManagerSecret
	1,  // 3: mcpany.config.v1.VaultSecret.token:type_name -> mcpany.config.v1.SecretValue
	5,  // 4: mcpany.config.v1.RemoteContent.auth:type_name -> mcpany.config.v1.Authentication
	6,  // 5: mcpany.config.v1.Authentication.api_key:type_name -> mcpany.config.v1.APIKeyAuth
	7,  // 6: mcpany.config.v1.Authentication.bearer_token:type_name -> mcpany.config.v1.BearerTokenAuth
	8,  // 7: mcpany.config.v1.Authentication.basic_auth:type_name -> mcpany.config.v1.BasicAuth
	9,  // 8: mcpany.config.v1.Authentication.oauth2:type_name -> mcpany.config.v1.OAuth2Auth
	10, // 9: mcpany.config.v1.Authentication.oidc:type_name -> mcpany.config.v1.OIDCAuth
	11, // 10: mcpany.config.v1.Authentication.mtls:type_name -> mcpany.config.v1.MTLSAuth
	12, // 11: mcpany.config.v1.Authentication.trusted_header:type_name -> mcpany.config.v1.TrustedHeaderAuth
	0,  // 12: mcpany.config.v1.APIKeyAuth.in:type_name -> mcpany.config.v1.APIKeyAuth.Location
	1,  // 13: mcpany.config.v1.APIKeyAuth.value:type_name -> mcpany.config.v1.SecretValue
	1,  // 14: mcpany.config.v1.BearerTokenAuth.token:type_name -> mcpany.config.v1.SecretValue
	1,  // 15: mcpany.config.v1.BasicAuth.password:type_name -> mcpany.config.v1.SecretValue
	1,  // 16: mcpany.config.v1.OAuth2Auth.client_id:type_name -> mcpany.config.v1.SecretValue
	1,  // 17: mcpany.config.v1.OAuth2Auth.client_secret:type_name -> mcpany.config.v1.SecretValue
	5,  // 18: mcpany.config.v1.Credential.authentication:type_name -> mcpany.config.v1.Authentication
	13, // 19: mcpany.config.v1.Credential.token:type_name -> mcpany.config.v1.UserToken
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_config_v1_auth_proto_init() }
func file_proto_config_v1_auth_proto_init() {
	if File_proto_config_v1_auth_proto != nil {
		return
	}
	file_proto_config_v1_auth_proto_msgTypes[0].OneofWrappers = []any{
		(*secretValue_PlainText)(nil),
		(*secretValue_EnvironmentVariable)(nil),
		(*secretValue_FilePath)(nil),
		(*secretValue_RemoteContent)(nil),
		(*secretValue_Vault)(nil),
		(*secretValue_AwsSecretManager)(nil),
	}
	file_proto_config_v1_auth_proto_msgTypes[4].OneofWrappers = []any{
		(*authentication_ApiKey)(nil),
		(*authentication_BearerToken)(nil),
		(*authentication_BasicAuth)(nil),
		(*authentication_Oauth2)(nil),
		(*authentication_Oidc)(nil),
		(*authentication_Mtls)(nil),
		(*authentication_TrustedHeader)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_v1_auth_proto_rawDesc), len(file_proto_config_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_config_v1_auth_proto_goTypes,
		DependencyIndexes: file_proto_config_v1_auth_proto_depIdxs,
		EnumInfos:         file_proto_config_v1_auth_proto_enumTypes,
		MessageInfos:      file_proto_config_v1_auth_proto_msgTypes,
	}.Build()
	File_proto_config_v1_auth_proto = out.File
	file_proto_config_v1_auth_proto_goTypes = nil
	file_proto_config_v1_auth_proto_depIdxs = nil
}
