# Copyright 2026 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

load("@aspect_bazel_lib//lib:directory_path.bzl", "directory_path")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_library")
load("@rules_go//go:def.bzl", "go_library")
load("@rules_go//proto:def.bzl", "go_proto_library")
load("@aspect_rules_ts//ts/private:ts_proto_library.bzl", ts_proto_library_rule = "ts_proto_library")

proto_library(
    name = "v1_proto",
    srcs = [
        "auth.proto",
        "call.proto",
        "collection.proto",
        "config.proto",
        "health_check.proto",
        "profile.proto",
        "prompt.proto",
        "resource.proto",
        "service_template.proto",
        "skill.proto",
        "tool.proto",
        "upstream_service.proto",
        "user.proto",
        "webhook.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//proto/bus:bus_proto",
        "@protobuf//:duration_proto",
        "@protobuf//:go_features_proto",
        "@protobuf//:struct_proto",
        "@protobuf//:timestamp_proto",
    ],
)

directory_path(
    name = "_v1_ts_proto.gen_es__entry_point",
    tags = ["manual"],
    directory = "//ui:node_modules/@bufbuild/protoc-gen-es/dir",
    path = "bin/protoc-gen-es",
)

js_binary(
    name = "_v1_ts_proto.gen_es",
    data = ["//ui:node_modules/@bufbuild/protoc-gen-es"],
    entry_point = ":_v1_ts_proto.gen_es__entry_point",
)

directory_path(
    name = "_v1_ts_proto.gen_connect_es__entry_point",
    tags = ["manual"],
    directory = "//ui:node_modules/@connectrpc/protoc-gen-connect-es/dir",
    path = "bin/protoc-gen-connect-es",
)

js_binary(
    name = "_v1_ts_proto.gen_connect_es",
    data = ["//ui:node_modules/@connectrpc/protoc-gen-connect-es"],
    entry_point = ":_v1_ts_proto.gen_connect_es__entry_point",
)

ts_proto_library_rule(
    name = "_v1_ts_proto_protoc",
    proto = ":v1_proto",
    protoc_gen_connect_es = ":_v1_ts_proto.gen_connect_es",
    protoc_gen_es = ":_v1_ts_proto.gen_es",
)

js_library(
    name = "v1_ts_proto",
    srcs = [":_v1_ts_proto_protoc"],
    deps = ["//ui:node_modules/@bufbuild/protobuf"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "v1_go_proto",
    compilers = ["@rules_go//proto:go_proto"],
    importpath = "github.com/mcpany/core/proto/config/v1",
    proto = ":v1_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//proto/bus",
        "@org_golang_google_protobuf//types/gofeaturespb",
    ],
)

go_library(
    name = "config",
    embed = [":v1_go_proto"],
    importpath = "github.com/mcpany/core/proto/config/v1",
    visibility = ["//visibility:public"],
)
