// Copyright 2026 Author(s) of MCP Any
// SPDX-License-Identifier: Apache-2.0
// TypeScript declaration stubs for proto/config/v1/call.proto
// These declarations provide type information for the Bazel build environment.
// The full implementation is generated by ts-proto via `make gen`.

export declare enum ParameterType {
  STRING = 0,
  NUMBER = 1,
  INTEGER = 2,
  BOOLEAN = 3,
  ARRAY = 4,
  OBJECT = 5,
}

export declare enum HttpCallDefinition_HttpMethod {
  HTTP_METHOD_UNSPECIFIED = 0,
  HTTP_METHOD_GET = 1,
  HTTP_METHOD_POST = 2,
  HTTP_METHOD_PUT = 3,
  HTTP_METHOD_DELETE = 4,
  HTTP_METHOD_PATCH = 5,
}

export interface ParameterSchema {
  name?: string;
  description?: string;
  type?: ParameterType;
  required?: boolean;
  defaultValue?: string;
  enum?: string[];
}

export interface HttpParameterMapping {
  schema?: ParameterSchema;
  location?: string;
  paramName?: string;
  template?: string;
}

export interface InputTransformer {
  template?: string;
  parameters?: HttpParameterMapping[];
}

export declare namespace OutputTransformer {
  export enum OutputFormat {
    JSON = 0,
    XML = 1,
    TEXT = 2,
    RAW_BYTES = 3,
    JQ = 4,
  }
}

export declare enum OutputTransformer_OutputFormat {
  JSON = 0,
  XML = 1,
  TEXT = 2,
  RAW_BYTES = 3,
  JQ = 4,
}

export interface OutputTransformer {
  format?: OutputTransformer_OutputFormat;
  expression?: string;
  resultTemplate?: string;
}

export interface HttpCallDefinition {
  id?: string;
  name?: string;
  description?: string;
  method?: HttpCallDefinition_HttpMethod;
  urlTemplate?: string;
  headers?: Record<string, string>;
  parameters?: HttpParameterMapping[];
  inputTransformer?: InputTransformer;
  outputTransformer?: OutputTransformer;
}
