// Copyright 2025 Author(s) of MCP Any
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/config/v1/middleware.proto

//go:build protoopaque

package v1

import (
	bus "github.com/mcpany/core/proto/bus"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateLimitConfig_Storage int32

const (
	RateLimitConfig_STORAGE_UNSPECIFIED RateLimitConfig_Storage = 0
	RateLimitConfig_STORAGE_MEMORY      RateLimitConfig_Storage = 1
	RateLimitConfig_STORAGE_REDIS       RateLimitConfig_Storage = 2
)

// Enum value maps for RateLimitConfig_Storage.
var (
	RateLimitConfig_Storage_name = map[int32]string{
		0: "STORAGE_UNSPECIFIED",
		1: "STORAGE_MEMORY",
		2: "STORAGE_REDIS",
	}
	RateLimitConfig_Storage_value = map[string]int32{
		"STORAGE_UNSPECIFIED": 0,
		"STORAGE_MEMORY":      1,
		"STORAGE_REDIS":       2,
	}
)

func (x RateLimitConfig_Storage) Enum() *RateLimitConfig_Storage {
	p := new(RateLimitConfig_Storage)
	*p = x
	return p
}

func (x RateLimitConfig_Storage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateLimitConfig_Storage) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_config_v1_middleware_proto_enumTypes[0].Descriptor()
}

func (RateLimitConfig_Storage) Type() protoreflect.EnumType {
	return &file_proto_config_v1_middleware_proto_enumTypes[0]
}

func (x RateLimitConfig_Storage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type CallPolicy_Action int32

const (
	CallPolicy_ALLOW        CallPolicy_Action = 0
	CallPolicy_DENY         CallPolicy_Action = 1
	CallPolicy_SAVE_CACHE   CallPolicy_Action = 2
	CallPolicy_DELETE_CACHE CallPolicy_Action = 3
)

// Enum value maps for CallPolicy_Action.
var (
	CallPolicy_Action_name = map[int32]string{
		0: "ALLOW",
		1: "DENY",
		2: "SAVE_CACHE",
		3: "DELETE_CACHE",
	}
	CallPolicy_Action_value = map[string]int32{
		"ALLOW":        0,
		"DENY":         1,
		"SAVE_CACHE":   2,
		"DELETE_CACHE": 3,
	}
)

func (x CallPolicy_Action) Enum() *CallPolicy_Action {
	p := new(CallPolicy_Action)
	*p = x
	return p
}

func (x CallPolicy_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallPolicy_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_config_v1_middleware_proto_enumTypes[1].Descriptor()
}

func (CallPolicy_Action) Type() protoreflect.EnumType {
	return &file_proto_config_v1_middleware_proto_enumTypes[1]
}

func (x CallPolicy_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Middleware struct {
	state                       protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Name             *string                       `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_MiddlewareConfig isMiddleware_MiddlewareConfig `protobuf_oneof:"middleware_config"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Middleware) Reset() {
	*x = Middleware{}
	mi := &file_proto_config_v1_middleware_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Middleware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Middleware) ProtoMessage() {}

func (x *Middleware) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_middleware_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Middleware) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Middleware) GetRateLimit() *RateLimitConfig {
	if x != nil {
		if x, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_RateLimit); ok {
			return x.RateLimit
		}
	}
	return nil
}

func (x *Middleware) GetCache() *CacheConfig {
	if x != nil {
		if x, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_Cache); ok {
			return x.Cache
		}
	}
	return nil
}

func (x *Middleware) GetAuthentication() *AuthenticationConfig {
	if x != nil {
		if x, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_Authentication); ok {
			return x.Authentication
		}
	}
	return nil
}

func (x *Middleware) GetAudit() *AuditConfig {
	if x != nil {
		if x, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_Audit); ok {
			return x.Audit
		}
	}
	return nil
}

func (x *Middleware) GetCallPolicy() *CallPolicy {
	if x != nil {
		if x, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_CallPolicy); ok {
			return x.CallPolicy
		}
	}
	return nil
}

func (x *Middleware) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Middleware) SetRateLimit(v *RateLimitConfig) {
	if v == nil {
		x.xxx_hidden_MiddlewareConfig = nil
		return
	}
	x.xxx_hidden_MiddlewareConfig = &middleware_RateLimit{v}
}

func (x *Middleware) SetCache(v *CacheConfig) {
	if v == nil {
		x.xxx_hidden_MiddlewareConfig = nil
		return
	}
	x.xxx_hidden_MiddlewareConfig = &middleware_Cache{v}
}

func (x *Middleware) SetAuthentication(v *AuthenticationConfig) {
	if v == nil {
		x.xxx_hidden_MiddlewareConfig = nil
		return
	}
	x.xxx_hidden_MiddlewareConfig = &middleware_Authentication{v}
}

func (x *Middleware) SetAudit(v *AuditConfig) {
	if v == nil {
		x.xxx_hidden_MiddlewareConfig = nil
		return
	}
	x.xxx_hidden_MiddlewareConfig = &middleware_Audit{v}
}

func (x *Middleware) SetCallPolicy(v *CallPolicy) {
	if v == nil {
		x.xxx_hidden_MiddlewareConfig = nil
		return
	}
	x.xxx_hidden_MiddlewareConfig = &middleware_CallPolicy{v}
}

func (x *Middleware) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Middleware) HasMiddlewareConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MiddlewareConfig != nil
}

func (x *Middleware) HasRateLimit() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_RateLimit)
	return ok
}

func (x *Middleware) HasCache() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_Cache)
	return ok
}

func (x *Middleware) HasAuthentication() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_Authentication)
	return ok
}

func (x *Middleware) HasAudit() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_Audit)
	return ok
}

func (x *Middleware) HasCallPolicy() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_CallPolicy)
	return ok
}

func (x *Middleware) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Middleware) ClearMiddlewareConfig() {
	x.xxx_hidden_MiddlewareConfig = nil
}

func (x *Middleware) ClearRateLimit() {
	if _, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_RateLimit); ok {
		x.xxx_hidden_MiddlewareConfig = nil
	}
}

func (x *Middleware) ClearCache() {
	if _, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_Cache); ok {
		x.xxx_hidden_MiddlewareConfig = nil
	}
}

func (x *Middleware) ClearAuthentication() {
	if _, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_Authentication); ok {
		x.xxx_hidden_MiddlewareConfig = nil
	}
}

func (x *Middleware) ClearAudit() {
	if _, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_Audit); ok {
		x.xxx_hidden_MiddlewareConfig = nil
	}
}

func (x *Middleware) ClearCallPolicy() {
	if _, ok := x.xxx_hidden_MiddlewareConfig.(*middleware_CallPolicy); ok {
		x.xxx_hidden_MiddlewareConfig = nil
	}
}

const Middleware_MiddlewareConfig_not_set_case case_Middleware_MiddlewareConfig = 0
const Middleware_RateLimit_case case_Middleware_MiddlewareConfig = 2
const Middleware_Cache_case case_Middleware_MiddlewareConfig = 3
const Middleware_Authentication_case case_Middleware_MiddlewareConfig = 4
const Middleware_Audit_case case_Middleware_MiddlewareConfig = 5
const Middleware_CallPolicy_case case_Middleware_MiddlewareConfig = 6

func (x *Middleware) WhichMiddlewareConfig() case_Middleware_MiddlewareConfig {
	if x == nil {
		return Middleware_MiddlewareConfig_not_set_case
	}
	switch x.xxx_hidden_MiddlewareConfig.(type) {
	case *middleware_RateLimit:
		return Middleware_RateLimit_case
	case *middleware_Cache:
		return Middleware_Cache_case
	case *middleware_Authentication:
		return Middleware_Authentication_case
	case *middleware_Audit:
		return Middleware_Audit_case
	case *middleware_CallPolicy:
		return Middleware_CallPolicy_case
	default:
		return Middleware_MiddlewareConfig_not_set_case
	}
}

type Middleware_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
	// Fields of oneof xxx_hidden_MiddlewareConfig:
	RateLimit      *RateLimitConfig
	Cache          *CacheConfig
	Authentication *AuthenticationConfig
	Audit          *AuditConfig
	CallPolicy     *CallPolicy
	// -- end of xxx_hidden_MiddlewareConfig
}

func (b0 Middleware_builder) Build() *Middleware {
	m0 := &Middleware{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.RateLimit != nil {
		x.xxx_hidden_MiddlewareConfig = &middleware_RateLimit{b.RateLimit}
	}
	if b.Cache != nil {
		x.xxx_hidden_MiddlewareConfig = &middleware_Cache{b.Cache}
	}
	if b.Authentication != nil {
		x.xxx_hidden_MiddlewareConfig = &middleware_Authentication{b.Authentication}
	}
	if b.Audit != nil {
		x.xxx_hidden_MiddlewareConfig = &middleware_Audit{b.Audit}
	}
	if b.CallPolicy != nil {
		x.xxx_hidden_MiddlewareConfig = &middleware_CallPolicy{b.CallPolicy}
	}
	return m0
}

type case_Middleware_MiddlewareConfig protoreflect.FieldNumber

func (x case_Middleware_MiddlewareConfig) String() string {
	md := file_proto_config_v1_middleware_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isMiddleware_MiddlewareConfig interface {
	isMiddleware_MiddlewareConfig()
}

type middleware_RateLimit struct {
	RateLimit *RateLimitConfig `protobuf:"bytes,2,opt,name=rate_limit,json=rateLimit,oneof"`
}

type middleware_Cache struct {
	Cache *CacheConfig `protobuf:"bytes,3,opt,name=cache,oneof"`
}

type middleware_Authentication struct {
	Authentication *AuthenticationConfig `protobuf:"bytes,4,opt,name=authentication,oneof"`
}

type middleware_Audit struct {
	Audit *AuditConfig `protobuf:"bytes,5,opt,name=audit,oneof"`
}

type middleware_CallPolicy struct {
	CallPolicy *CallPolicy `protobuf:"bytes,6,opt,name=call_policy,json=callPolicy,oneof"`
}

func (*middleware_RateLimit) isMiddleware_MiddlewareConfig() {}

func (*middleware_Cache) isMiddleware_MiddlewareConfig() {}

func (*middleware_Authentication) isMiddleware_MiddlewareConfig() {}

func (*middleware_Audit) isMiddleware_MiddlewareConfig() {}

func (*middleware_CallPolicy) isMiddleware_MiddlewareConfig() {}

// Configuration for rate limiting requests to the upstream service.
type RateLimitConfig struct {
	state                        protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_IsEnabled         bool                    `protobuf:"varint,1,opt,name=is_enabled"`
	xxx_hidden_RequestsPerSecond float64                 `protobuf:"fixed64,2,opt,name=requests_per_second"`
	xxx_hidden_Burst             int64                   `protobuf:"varint,3,opt,name=burst"`
	xxx_hidden_Storage           RateLimitConfig_Storage `protobuf:"varint,4,opt,name=storage,enum=mcpany.config.v1.RateLimitConfig_Storage"`
	xxx_hidden_Redis             *bus.RedisBus           `protobuf:"bytes,5,opt,name=redis"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RateLimitConfig) Reset() {
	*x = RateLimitConfig{}
	mi := &file_proto_config_v1_middleware_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitConfig) ProtoMessage() {}

func (x *RateLimitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_middleware_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RateLimitConfig) GetIsEnabled() bool {
	if x != nil {
		return x.xxx_hidden_IsEnabled
	}
	return false
}

func (x *RateLimitConfig) GetRequestsPerSecond() float64 {
	if x != nil {
		return x.xxx_hidden_RequestsPerSecond
	}
	return 0
}

func (x *RateLimitConfig) GetBurst() int64 {
	if x != nil {
		return x.xxx_hidden_Burst
	}
	return 0
}

func (x *RateLimitConfig) GetStorage() RateLimitConfig_Storage {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_Storage
		}
	}
	return RateLimitConfig_STORAGE_UNSPECIFIED
}

func (x *RateLimitConfig) GetRedis() *bus.RedisBus {
	if x != nil {
		return x.xxx_hidden_Redis
	}
	return nil
}

func (x *RateLimitConfig) SetIsEnabled(v bool) {
	x.xxx_hidden_IsEnabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *RateLimitConfig) SetRequestsPerSecond(v float64) {
	x.xxx_hidden_RequestsPerSecond = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *RateLimitConfig) SetBurst(v int64) {
	x.xxx_hidden_Burst = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *RateLimitConfig) SetStorage(v RateLimitConfig_Storage) {
	x.xxx_hidden_Storage = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *RateLimitConfig) SetRedis(v *bus.RedisBus) {
	x.xxx_hidden_Redis = v
}

func (x *RateLimitConfig) HasIsEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RateLimitConfig) HasRequestsPerSecond() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RateLimitConfig) HasBurst() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RateLimitConfig) HasStorage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RateLimitConfig) HasRedis() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Redis != nil
}

func (x *RateLimitConfig) ClearIsEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_IsEnabled = false
}

func (x *RateLimitConfig) ClearRequestsPerSecond() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RequestsPerSecond = 0
}

func (x *RateLimitConfig) ClearBurst() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Burst = 0
}

func (x *RateLimitConfig) ClearStorage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Storage = RateLimitConfig_STORAGE_UNSPECIFIED
}

func (x *RateLimitConfig) ClearRedis() {
	x.xxx_hidden_Redis = nil
}

type RateLimitConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether rate limiting is enabled.
	IsEnabled *bool
	// The maximum number of requests allowed per second.
	RequestsPerSecond *float64
	// The number of requests that can be allowed in a short burst.
	Burst   *int64
	Storage *RateLimitConfig_Storage
	// Redis configuration if storage is set to STORAGE_REDIS.
	Redis *bus.RedisBus
}

func (b0 RateLimitConfig_builder) Build() *RateLimitConfig {
	m0 := &RateLimitConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.IsEnabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_IsEnabled = *b.IsEnabled
	}
	if b.RequestsPerSecond != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_RequestsPerSecond = *b.RequestsPerSecond
	}
	if b.Burst != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Burst = *b.Burst
	}
	if b.Storage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Storage = *b.Storage
	}
	x.xxx_hidden_Redis = b.Redis
	return m0
}

type AuditConfig struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled      bool                   `protobuf:"varint,1,opt,name=enabled"`
	xxx_hidden_OutputPath   *string                `protobuf:"bytes,2,opt,name=output_path"`
	xxx_hidden_LogArguments bool                   `protobuf:"varint,3,opt,name=log_arguments"`
	xxx_hidden_LogResults   bool                   `protobuf:"varint,4,opt,name=log_results"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuditConfig) Reset() {
	*x = AuditConfig{}
	mi := &file_proto_config_v1_middleware_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditConfig) ProtoMessage() {}

func (x *AuditConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_middleware_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuditConfig) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *AuditConfig) GetOutputPath() string {
	if x != nil {
		if x.xxx_hidden_OutputPath != nil {
			return *x.xxx_hidden_OutputPath
		}
		return ""
	}
	return ""
}

func (x *AuditConfig) GetLogArguments() bool {
	if x != nil {
		return x.xxx_hidden_LogArguments
	}
	return false
}

func (x *AuditConfig) GetLogResults() bool {
	if x != nil {
		return x.xxx_hidden_LogResults
	}
	return false
}

func (x *AuditConfig) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *AuditConfig) SetOutputPath(v string) {
	x.xxx_hidden_OutputPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *AuditConfig) SetLogArguments(v bool) {
	x.xxx_hidden_LogArguments = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *AuditConfig) SetLogResults(v bool) {
	x.xxx_hidden_LogResults = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *AuditConfig) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuditConfig) HasOutputPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuditConfig) HasLogArguments() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AuditConfig) HasLogResults() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AuditConfig) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Enabled = false
}

func (x *AuditConfig) ClearOutputPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OutputPath = nil
}

func (x *AuditConfig) ClearLogArguments() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_LogArguments = false
}

func (x *AuditConfig) ClearLogResults() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_LogResults = false
}

type AuditConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether audit logging is enabled.
	Enabled *bool
	// The file path to write audit logs to.
	OutputPath *string
	// Whether to log input arguments (caution: might contain secrets).
	LogArguments *bool
	// Whether to log output results (caution: might contain sensitive data).
	LogResults *bool
}

func (b0 AuditConfig_builder) Build() *AuditConfig {
	m0 := &AuditConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.OutputPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_OutputPath = b.OutputPath
	}
	if b.LogArguments != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_LogArguments = *b.LogArguments
	}
	if b.LogResults != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_LogResults = *b.LogResults
	}
	return m0
}

type CallPolicy struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DefaultAction CallPolicy_Action      `protobuf:"varint,1,opt,name=default_action,json=defaultAction,enum=mcpany.config.v1.CallPolicy_Action"`
	xxx_hidden_Rules         *[]*CallPolicyRule     `protobuf:"bytes,2,rep,name=rules"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CallPolicy) Reset() {
	*x = CallPolicy{}
	mi := &file_proto_config_v1_middleware_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPolicy) ProtoMessage() {}

func (x *CallPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_middleware_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CallPolicy) GetDefaultAction() CallPolicy_Action {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_DefaultAction
		}
	}
	return CallPolicy_ALLOW
}

func (x *CallPolicy) GetRules() []*CallPolicyRule {
	if x != nil {
		if x.xxx_hidden_Rules != nil {
			return *x.xxx_hidden_Rules
		}
	}
	return nil
}

func (x *CallPolicy) SetDefaultAction(v CallPolicy_Action) {
	x.xxx_hidden_DefaultAction = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CallPolicy) SetRules(v []*CallPolicyRule) {
	x.xxx_hidden_Rules = &v
}

func (x *CallPolicy) HasDefaultAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CallPolicy) ClearDefaultAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DefaultAction = CallPolicy_ALLOW
}

type CallPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Default action if no rules match.
	DefaultAction *CallPolicy_Action
	// List of rules to apply. First match wins.
	Rules []*CallPolicyRule
}

func (b0 CallPolicy_builder) Build() *CallPolicy {
	m0 := &CallPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DefaultAction != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_DefaultAction = *b.DefaultAction
	}
	x.xxx_hidden_Rules = &b.Rules
	return m0
}

type CallPolicyRule struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Action        CallPolicy_Action      `protobuf:"varint,1,opt,name=action,enum=mcpany.config.v1.CallPolicy_Action"`
	xxx_hidden_NameRegex     *string                `protobuf:"bytes,2,opt,name=name_regex"`
	xxx_hidden_ArgumentRegex *string                `protobuf:"bytes,3,opt,name=argument_regex,json=argumentRegex"`
	xxx_hidden_UrlRegex      *string                `protobuf:"bytes,4,opt,name=url_regex"`
	xxx_hidden_CallIdRegex   *string                `protobuf:"bytes,5,opt,name=call_id_regex"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CallPolicyRule) Reset() {
	*x = CallPolicyRule{}
	mi := &file_proto_config_v1_middleware_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPolicyRule) ProtoMessage() {}

func (x *CallPolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_middleware_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CallPolicyRule) GetAction() CallPolicy_Action {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Action
		}
	}
	return CallPolicy_ALLOW
}

func (x *CallPolicyRule) GetNameRegex() string {
	if x != nil {
		if x.xxx_hidden_NameRegex != nil {
			return *x.xxx_hidden_NameRegex
		}
		return ""
	}
	return ""
}

func (x *CallPolicyRule) GetArgumentRegex() string {
	if x != nil {
		if x.xxx_hidden_ArgumentRegex != nil {
			return *x.xxx_hidden_ArgumentRegex
		}
		return ""
	}
	return ""
}

func (x *CallPolicyRule) GetUrlRegex() string {
	if x != nil {
		if x.xxx_hidden_UrlRegex != nil {
			return *x.xxx_hidden_UrlRegex
		}
		return ""
	}
	return ""
}

func (x *CallPolicyRule) GetCallIdRegex() string {
	if x != nil {
		if x.xxx_hidden_CallIdRegex != nil {
			return *x.xxx_hidden_CallIdRegex
		}
		return ""
	}
	return ""
}

func (x *CallPolicyRule) SetAction(v CallPolicy_Action) {
	x.xxx_hidden_Action = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *CallPolicyRule) SetNameRegex(v string) {
	x.xxx_hidden_NameRegex = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *CallPolicyRule) SetArgumentRegex(v string) {
	x.xxx_hidden_ArgumentRegex = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *CallPolicyRule) SetUrlRegex(v string) {
	x.xxx_hidden_UrlRegex = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *CallPolicyRule) SetCallIdRegex(v string) {
	x.xxx_hidden_CallIdRegex = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *CallPolicyRule) HasAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CallPolicyRule) HasNameRegex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CallPolicyRule) HasArgumentRegex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CallPolicyRule) HasUrlRegex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CallPolicyRule) HasCallIdRegex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CallPolicyRule) ClearAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Action = CallPolicy_ALLOW
}

func (x *CallPolicyRule) ClearNameRegex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NameRegex = nil
}

func (x *CallPolicyRule) ClearArgumentRegex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ArgumentRegex = nil
}

func (x *CallPolicyRule) ClearUrlRegex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_UrlRegex = nil
}

func (x *CallPolicyRule) ClearCallIdRegex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_CallIdRegex = nil
}

type CallPolicyRule_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Action *CallPolicy_Action
	// Regex to match the call name. Empty means match all.
	NameRegex *string
	// Regex to match request arguments (JSON stringified). Empty means match all.
	// This is a simple regex match on the JSON representation of arguments.
	ArgumentRegex *string
	// Regex to match endpoint path or URL.
	UrlRegex *string
	// Regex to match call ID. Empty means match all.
	CallIdRegex *string
}

func (b0 CallPolicyRule_builder) Build() *CallPolicyRule {
	m0 := &CallPolicyRule{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Action != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Action = *b.Action
	}
	if b.NameRegex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_NameRegex = b.NameRegex
	}
	if b.ArgumentRegex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_ArgumentRegex = b.ArgumentRegex
	}
	if b.UrlRegex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_UrlRegex = b.UrlRegex
	}
	if b.CallIdRegex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_CallIdRegex = b.CallIdRegex
	}
	return m0
}

type CallHook struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_HookConfig  isCallHook_HookConfig  `protobuf_oneof:"hook_config"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CallHook) Reset() {
	*x = CallHook{}
	mi := &file_proto_config_v1_middleware_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallHook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallHook) ProtoMessage() {}

func (x *CallHook) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_middleware_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CallHook) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *CallHook) GetWebhook() *WebhookConfig {
	if x != nil {
		if x, ok := x.xxx_hidden_HookConfig.(*callHook_Webhook); ok {
			return x.Webhook
		}
	}
	return nil
}

func (x *CallHook) GetCallPolicy() *CallPolicy {
	if x != nil {
		if x, ok := x.xxx_hidden_HookConfig.(*callHook_CallPolicy); ok {
			return x.CallPolicy
		}
	}
	return nil
}

func (x *CallHook) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CallHook) SetWebhook(v *WebhookConfig) {
	if v == nil {
		x.xxx_hidden_HookConfig = nil
		return
	}
	x.xxx_hidden_HookConfig = &callHook_Webhook{v}
}

func (x *CallHook) SetCallPolicy(v *CallPolicy) {
	if v == nil {
		x.xxx_hidden_HookConfig = nil
		return
	}
	x.xxx_hidden_HookConfig = &callHook_CallPolicy{v}
}

func (x *CallHook) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CallHook) HasHookConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HookConfig != nil
}

func (x *CallHook) HasWebhook() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_HookConfig.(*callHook_Webhook)
	return ok
}

func (x *CallHook) HasCallPolicy() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_HookConfig.(*callHook_CallPolicy)
	return ok
}

func (x *CallHook) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *CallHook) ClearHookConfig() {
	x.xxx_hidden_HookConfig = nil
}

func (x *CallHook) ClearWebhook() {
	if _, ok := x.xxx_hidden_HookConfig.(*callHook_Webhook); ok {
		x.xxx_hidden_HookConfig = nil
	}
}

func (x *CallHook) ClearCallPolicy() {
	if _, ok := x.xxx_hidden_HookConfig.(*callHook_CallPolicy); ok {
		x.xxx_hidden_HookConfig = nil
	}
}

const CallHook_HookConfig_not_set_case case_CallHook_HookConfig = 0
const CallHook_Webhook_case case_CallHook_HookConfig = 2
const CallHook_CallPolicy_case case_CallHook_HookConfig = 4

func (x *CallHook) WhichHookConfig() case_CallHook_HookConfig {
	if x == nil {
		return CallHook_HookConfig_not_set_case
	}
	switch x.xxx_hidden_HookConfig.(type) {
	case *callHook_Webhook:
		return CallHook_Webhook_case
	case *callHook_CallPolicy:
		return CallHook_CallPolicy_case
	default:
		return CallHook_HookConfig_not_set_case
	}
}

type CallHook_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
	// Fields of oneof xxx_hidden_HookConfig:
	Webhook    *WebhookConfig
	CallPolicy *CallPolicy
	// -- end of xxx_hidden_HookConfig
}

func (b0 CallHook_builder) Build() *CallHook {
	m0 := &CallHook{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.Webhook != nil {
		x.xxx_hidden_HookConfig = &callHook_Webhook{b.Webhook}
	}
	if b.CallPolicy != nil {
		x.xxx_hidden_HookConfig = &callHook_CallPolicy{b.CallPolicy}
	}
	return m0
}

type case_CallHook_HookConfig protoreflect.FieldNumber

func (x case_CallHook_HookConfig) String() string {
	md := file_proto_config_v1_middleware_proto_msgTypes[5].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isCallHook_HookConfig interface {
	isCallHook_HookConfig()
}

type callHook_Webhook struct {
	Webhook *WebhookConfig `protobuf:"bytes,2,opt,name=webhook,oneof"`
}

type callHook_CallPolicy struct {
	CallPolicy *CallPolicy `protobuf:"bytes,4,opt,name=call_policy,json=callPolicy,oneof"`
}

func (*callHook_Webhook) isCallHook_HookConfig() {}

func (*callHook_CallPolicy) isCallHook_HookConfig() {}

var File_proto_config_v1_middleware_proto protoreflect.FileDescriptor

const file_proto_config_v1_middleware_proto_rawDesc = "" +
	"\n" +
	" proto/config/v1/middleware.proto\x12\x10mcpany.config.v1\x1a\x13proto/bus/bus.proto\x1a\x1aproto/config/v1/auth.proto\x1a\x1aproto/config/v1/call.proto\x1a\x1dproto/config/v1/webhook.proto\"\xfa\x02\n" +
	"\n" +
	"Middleware\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12B\n" +
	"\n" +
	"rate_limit\x18\x02 \x01(\v2!.mcpany.config.v1.RateLimitConfigH\x00R\trateLimit\x125\n" +
	"\x05cache\x18\x03 \x01(\v2\x1d.mcpany.config.v1.CacheConfigH\x00R\x05cache\x12P\n" +
	"\x0eauthentication\x18\x04 \x01(\v2&.mcpany.config.v1.AuthenticationConfigH\x00R\x0eauthentication\x125\n" +
	"\x05audit\x18\x05 \x01(\v2\x1d.mcpany.config.v1.AuditConfigH\x00R\x05audit\x12?\n" +
	"\vcall_policy\x18\x06 \x01(\v2\x1c.mcpany.config.v1.CallPolicyH\x00R\n" +
	"callPolicyB\x13\n" +
	"\x11middleware_config\"\xae\x02\n" +
	"\x0fRateLimitConfig\x12\x1e\n" +
	"\n" +
	"is_enabled\x18\x01 \x01(\bR\n" +
	"is_enabled\x120\n" +
	"\x13requests_per_second\x18\x02 \x01(\x01R\x13requests_per_second\x12\x14\n" +
	"\x05burst\x18\x03 \x01(\x03R\x05burst\x12C\n" +
	"\astorage\x18\x04 \x01(\x0e2).mcpany.config.v1.RateLimitConfig.StorageR\astorage\x12#\n" +
	"\x05redis\x18\x05 \x01(\v2\r.bus.RedisBusR\x05redis\"I\n" +
	"\aStorage\x12\x17\n" +
	"\x13STORAGE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTORAGE_MEMORY\x10\x01\x12\x11\n" +
	"\rSTORAGE_REDIS\x10\x02\"\x91\x01\n" +
	"\vAuditConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12 \n" +
	"\voutput_path\x18\x02 \x01(\tR\voutput_path\x12$\n" +
	"\rlog_arguments\x18\x03 \x01(\bR\rlog_arguments\x12 \n" +
	"\vlog_results\x18\x04 \x01(\bR\vlog_results\"\xd1\x01\n" +
	"\n" +
	"CallPolicy\x12J\n" +
	"\x0edefault_action\x18\x01 \x01(\x0e2#.mcpany.config.v1.CallPolicy.ActionR\rdefaultAction\x126\n" +
	"\x05rules\x18\x02 \x03(\v2 .mcpany.config.v1.CallPolicyRuleR\x05rules\"?\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\b\n" +
	"\x04DENY\x10\x01\x12\x0e\n" +
	"\n" +
	"SAVE_CACHE\x10\x02\x12\x10\n" +
	"\fDELETE_CACHE\x10\x03\"\xd8\x01\n" +
	"\x0eCallPolicyRule\x12;\n" +
	"\x06action\x18\x01 \x01(\x0e2#.mcpany.config.v1.CallPolicy.ActionR\x06action\x12\x1e\n" +
	"\n" +
	"name_regex\x18\x02 \x01(\tR\n" +
	"name_regex\x12%\n" +
	"\x0eargument_regex\x18\x03 \x01(\tR\rargumentRegex\x12\x1c\n" +
	"\turl_regex\x18\x04 \x01(\tR\turl_regex\x12$\n" +
	"\rcall_id_regex\x18\x05 \x01(\tR\rcall_id_regex\"\xab\x01\n" +
	"\bCallHook\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\awebhook\x18\x02 \x01(\v2\x1f.mcpany.config.v1.WebhookConfigH\x00R\awebhook\x12?\n" +
	"\vcall_policy\x18\x04 \x01(\v2\x1c.mcpany.config.v1.CallPolicyH\x00R\n" +
	"callPolicyB\r\n" +
	"\vhook_configB9B\x0fMiddlewareProtoZ&github.com/mcpany/core/proto/config/v1b\beditionsp\xe8\a"

var file_proto_config_v1_middleware_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_config_v1_middleware_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_config_v1_middleware_proto_goTypes = []any{
	(RateLimitConfig_Storage)(0), // 0: mcpany.config.v1.RateLimitConfig.Storage
	(CallPolicy_Action)(0),       // 1: mcpany.config.v1.CallPolicy.Action
	(*Middleware)(nil),           // 2: mcpany.config.v1.Middleware
	(*RateLimitConfig)(nil),      // 3: mcpany.config.v1.RateLimitConfig
	(*AuditConfig)(nil),          // 4: mcpany.config.v1.AuditConfig
	(*CallPolicy)(nil),           // 5: mcpany.config.v1.CallPolicy
	(*CallPolicyRule)(nil),       // 6: mcpany.config.v1.CallPolicyRule
	(*CallHook)(nil),             // 7: mcpany.config.v1.CallHook
	(*CacheConfig)(nil),          // 8: mcpany.config.v1.CacheConfig
	(*AuthenticationConfig)(nil), // 9: mcpany.config.v1.AuthenticationConfig
	(*bus.RedisBus)(nil),         // 10: bus.RedisBus
	(*WebhookConfig)(nil),        // 11: mcpany.config.v1.WebhookConfig
}
var file_proto_config_v1_middleware_proto_depIdxs = []int32{
	3,  // 0: mcpany.config.v1.Middleware.rate_limit:type_name -> mcpany.config.v1.RateLimitConfig
	8,  // 1: mcpany.config.v1.Middleware.cache:type_name -> mcpany.config.v1.CacheConfig
	9,  // 2: mcpany.config.v1.Middleware.authentication:type_name -> mcpany.config.v1.AuthenticationConfig
	4,  // 3: mcpany.config.v1.Middleware.audit:type_name -> mcpany.config.v1.AuditConfig
	5,  // 4: mcpany.config.v1.Middleware.call_policy:type_name -> mcpany.config.v1.CallPolicy
	0,  // 5: mcpany.config.v1.RateLimitConfig.storage:type_name -> mcpany.config.v1.RateLimitConfig.Storage
	10, // 6: mcpany.config.v1.RateLimitConfig.redis:type_name -> bus.RedisBus
	1,  // 7: mcpany.config.v1.CallPolicy.default_action:type_name -> mcpany.config.v1.CallPolicy.Action
	6,  // 8: mcpany.config.v1.CallPolicy.rules:type_name -> mcpany.config.v1.CallPolicyRule
	1,  // 9: mcpany.config.v1.CallPolicyRule.action:type_name -> mcpany.config.v1.CallPolicy.Action
	11, // 10: mcpany.config.v1.CallHook.webhook:type_name -> mcpany.config.v1.WebhookConfig
	5,  // 11: mcpany.config.v1.CallHook.call_policy:type_name -> mcpany.config.v1.CallPolicy
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_config_v1_middleware_proto_init() }
func file_proto_config_v1_middleware_proto_init() {
	if File_proto_config_v1_middleware_proto != nil {
		return
	}
	file_proto_config_v1_auth_proto_init()
	file_proto_config_v1_call_proto_init()
	file_proto_config_v1_webhook_proto_init()
	file_proto_config_v1_middleware_proto_msgTypes[0].OneofWrappers = []any{
		(*middleware_RateLimit)(nil),
		(*middleware_Cache)(nil),
		(*middleware_Authentication)(nil),
		(*middleware_Audit)(nil),
		(*middleware_CallPolicy)(nil),
	}
	file_proto_config_v1_middleware_proto_msgTypes[5].OneofWrappers = []any{
		(*callHook_Webhook)(nil),
		(*callHook_CallPolicy)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_v1_middleware_proto_rawDesc), len(file_proto_config_v1_middleware_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_config_v1_middleware_proto_goTypes,
		DependencyIndexes: file_proto_config_v1_middleware_proto_depIdxs,
		EnumInfos:         file_proto_config_v1_middleware_proto_enumTypes,
		MessageInfos:      file_proto_config_v1_middleware_proto_msgTypes,
	}.Build()
	File_proto_config_v1_middleware_proto = out.File
	file_proto_config_v1_middleware_proto_goTypes = nil
	file_proto_config_v1_middleware_proto_depIdxs = nil
}
