// Copyright (C) 2025 Author(s) of MCP Any
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/config/v1/prompt.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromptDefinition struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Template    *string                `protobuf:"bytes,2,opt,name=template"`
	xxx_hidden_Parameters  map[string]string      `protobuf:"bytes,3,rep,name=parameters" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PromptDefinition) Reset() {
	*x = PromptDefinition{}
	mi := &file_proto_config_v1_prompt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptDefinition) ProtoMessage() {}

func (x *PromptDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_prompt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PromptDefinition) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *PromptDefinition) GetTemplate() string {
	if x != nil {
		if x.xxx_hidden_Template != nil {
			return *x.xxx_hidden_Template
		}
		return ""
	}
	return ""
}

func (x *PromptDefinition) GetParameters() map[string]string {
	if x != nil {
		return x.xxx_hidden_Parameters
	}
	return nil
}

func (x *PromptDefinition) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *PromptDefinition) SetTemplate(v string) {
	x.xxx_hidden_Template = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *PromptDefinition) SetParameters(v map[string]string) {
	x.xxx_hidden_Parameters = v
}

func (x *PromptDefinition) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PromptDefinition) HasTemplate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PromptDefinition) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *PromptDefinition) ClearTemplate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Template = nil
}

type PromptDefinition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id         *string
	Template   *string
	Parameters map[string]string
}

func (b0 PromptDefinition_builder) Build() *PromptDefinition {
	m0 := &PromptDefinition{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	if b.Template != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Template = b.Template
	}
	x.xxx_hidden_Parameters = b.Parameters
	return m0
}

var File_proto_config_v1_prompt_proto protoreflect.FileDescriptor

const file_proto_config_v1_prompt_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/config/v1/prompt.proto\x12\x10mcpany.config.v1\"\xd1\x01\n" +
	"\x10PromptDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12R\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v22.mcpany.config.v1.PromptDefinition.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B(Z&github.com/mcpany/core/proto/config/v1b\beditionsp\xe8\a"

var file_proto_config_v1_prompt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_config_v1_prompt_proto_goTypes = []any{
	(*PromptDefinition)(nil), // 0: mcpany.config.v1.PromptDefinition
	nil,                      // 1: mcpany.config.v1.PromptDefinition.ParametersEntry
}
var file_proto_config_v1_prompt_proto_depIdxs = []int32{
	1, // 0: mcpany.config.v1.PromptDefinition.parameters:type_name -> mcpany.config.v1.PromptDefinition.ParametersEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_config_v1_prompt_proto_init() }
func file_proto_config_v1_prompt_proto_init() {
	if File_proto_config_v1_prompt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_v1_prompt_proto_rawDesc), len(file_proto_config_v1_prompt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_config_v1_prompt_proto_goTypes,
		DependencyIndexes: file_proto_config_v1_prompt_proto_depIdxs,
		MessageInfos:      file_proto_config_v1_prompt_proto_msgTypes,
	}.Build()
	File_proto_config_v1_prompt_proto = out.File
	file_proto_config_v1_prompt_proto_goTypes = nil
	file_proto_config_v1_prompt_proto_depIdxs = nil
}
