// Copyright 2026 Author(s) of MCP Any
// SPDX-License-Identifier: Apache-2.0
// TypeScript declaration stubs for proto/config/v1/prompt.proto
// These declarations provide type information for the Bazel build environment.
// The full implementation is generated by ts-proto via `make gen`.

export interface PromptArgument {
  name?: string;
  description?: string;
  required?: boolean;
}

export interface PromptMessage {
  role?: number;
  content?: unknown;
}

export interface PromptDefinition {
  name: string;
  title?: string;
  description?: string;
  inputSchema?: Record<string, unknown>;
  messages?: PromptMessage[];
  disable?: boolean;
  arguments?: PromptArgument[];
}
