// Copyright 2026 Author(s) of MCP Any
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/config/v1/skill.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Skill describes an Agent Skill, which provides instructions and assets to an agent.
type Skill struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Description  *string                `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_License      *string                `protobuf:"bytes,3,opt,name=license"`
	xxx_hidden_Instructions *string                `protobuf:"bytes,4,opt,name=instructions"`
	xxx_hidden_AllowedTools []string               `protobuf:"bytes,5,rep,name=allowed_tools"`
	xxx_hidden_Assets       []string               `protobuf:"bytes,6,rep,name=assets"`
	xxx_hidden_Metadata     map[string]string      `protobuf:"bytes,7,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_proto_config_v1_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Skill) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *Skill) GetLicense() string {
	if x != nil {
		if x.xxx_hidden_License != nil {
			return *x.xxx_hidden_License
		}
		return ""
	}
	return ""
}

func (x *Skill) GetInstructions() string {
	if x != nil {
		if x.xxx_hidden_Instructions != nil {
			return *x.xxx_hidden_Instructions
		}
		return ""
	}
	return ""
}

func (x *Skill) GetAllowedTools() []string {
	if x != nil {
		return x.xxx_hidden_AllowedTools
	}
	return nil
}

func (x *Skill) GetAssets() []string {
	if x != nil {
		return x.xxx_hidden_Assets
	}
	return nil
}

func (x *Skill) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Skill) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *Skill) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *Skill) SetLicense(v string) {
	x.xxx_hidden_License = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *Skill) SetInstructions(v string) {
	x.xxx_hidden_Instructions = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *Skill) SetAllowedTools(v []string) {
	x.xxx_hidden_AllowedTools = v
}

func (x *Skill) SetAssets(v []string) {
	x.xxx_hidden_Assets = v
}

func (x *Skill) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *Skill) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Skill) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Skill) HasLicense() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Skill) HasInstructions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Skill) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Skill) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Description = nil
}

func (x *Skill) ClearLicense() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_License = nil
}

func (x *Skill) ClearInstructions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Instructions = nil
}

type Skill_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier for the skill (e.g. "data-processing").
	Name *string
	// Human-readable description of the skill.
	Description *string
	// License information for the skill.
	License *string
	// Instructions for the agent on how to use this skill (Markdown).
	Instructions *string
	// List of tool names that this skill is allowed to use.
	AllowedTools []string
	// List of asset file paths associated with this skill (relative to skill root).
	Assets []string
	// Arbitrary metadata for the skill.
	Metadata map[string]string
}

func (b0 Skill_builder) Build() *Skill {
	m0 := &Skill{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Name = b.Name
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Description = b.Description
	}
	if b.License != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_License = b.License
	}
	if b.Instructions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Instructions = b.Instructions
	}
	x.xxx_hidden_AllowedTools = b.AllowedTools
	x.xxx_hidden_Assets = b.Assets
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

var File_proto_config_v1_skill_proto protoreflect.FileDescriptor

const file_proto_config_v1_skill_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/config/v1/skill.proto\x12\x10mcpany.config.v1\x1a!google/protobuf/go_features.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb9\x02\n" +
	"\x05Skill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\alicense\x18\x03 \x01(\tR\alicense\x12\"\n" +
	"\finstructions\x18\x04 \x01(\tR\finstructions\x12$\n" +
	"\rallowed_tools\x18\x05 \x03(\tR\rallowed_tools\x12\x16\n" +
	"\x06assets\x18\x06 \x03(\tR\x06assets\x12A\n" +
	"\bmetadata\x18\a \x03(\v2%.mcpany.config.v1.Skill.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B<B\n" +
	"SkillProtoZ&github.com/mcpany/core/proto/config/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_proto_config_v1_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_config_v1_skill_proto_goTypes = []any{
	(*Skill)(nil), // 0: mcpany.config.v1.Skill
	nil,           // 1: mcpany.config.v1.Skill.MetadataEntry
}
var file_proto_config_v1_skill_proto_depIdxs = []int32{
	1, // 0: mcpany.config.v1.Skill.metadata:type_name -> mcpany.config.v1.Skill.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_config_v1_skill_proto_init() }
func file_proto_config_v1_skill_proto_init() {
	if File_proto_config_v1_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_v1_skill_proto_rawDesc), len(file_proto_config_v1_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_config_v1_skill_proto_goTypes,
		DependencyIndexes: file_proto_config_v1_skill_proto_depIdxs,
		MessageInfos:      file_proto_config_v1_skill_proto_msgTypes,
	}.Build()
	File_proto_config_v1_skill_proto = out.File
	file_proto_config_v1_skill_proto_goTypes = nil
	file_proto_config_v1_skill_proto_depIdxs = nil
}
