// Copyright 2025 Author(s) of MCP Any
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/config/v1/resource.proto

//go:build !protoopaque

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceAnnotation struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// An array indicating the intended audience(s) for this
	// resource. Valid values are "user" and "assistant". For example,
	// ["user", "assistant"] indicates content useful for both.
	Audience []string `protobuf:"bytes,1,rep,name=audience" json:"audience,omitempty"`
	// A number from 0.0 to 1.0 indicating the importance of
	// this resource. A value of 1 means “most important” (effectively
	// required), while 0 means “least important” (entirely optional).
	Priority *float64 `protobuf:"fixed64,2,opt,name=priority" json:"priority,omitempty"`
	// An ISO 8601 formatted timestamp indicating when the
	// resource was last modified (e.g., "2025-01-12T15:00:58Z").
	LastModified  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_modified,json=lastModified" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceAnnotation) Reset() {
	*x = ResourceAnnotation{}
	mi := &file_proto_config_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAnnotation) ProtoMessage() {}

func (x *ResourceAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceAnnotation) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *ResourceAnnotation) GetPriority() float64 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *ResourceAnnotation) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

func (x *ResourceAnnotation) SetAudience(v []string) {
	x.Audience = v
}

func (x *ResourceAnnotation) SetPriority(v float64) {
	x.Priority = &v
}

func (x *ResourceAnnotation) SetLastModified(v *timestamppb.Timestamp) {
	x.LastModified = v
}

func (x *ResourceAnnotation) HasPriority() bool {
	if x == nil {
		return false
	}
	return x.Priority != nil
}

func (x *ResourceAnnotation) HasLastModified() bool {
	if x == nil {
		return false
	}
	return x.LastModified != nil
}

func (x *ResourceAnnotation) ClearPriority() {
	x.Priority = nil
}

func (x *ResourceAnnotation) ClearLastModified() {
	x.LastModified = nil
}

type ResourceAnnotation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// An array indicating the intended audience(s) for this
	// resource. Valid values are "user" and "assistant". For example,
	// ["user", "assistant"] indicates content useful for both.
	Audience []string
	// A number from 0.0 to 1.0 indicating the importance of
	// this resource. A value of 1 means “most important” (effectively
	// required), while 0 means “least important” (entirely optional).
	Priority *float64
	// An ISO 8601 formatted timestamp indicating when the
	// resource was last modified (e.g., "2025-01-12T15:00:58Z").
	LastModified *timestamppb.Timestamp
}

func (b0 ResourceAnnotation_builder) Build() *ResourceAnnotation {
	m0 := &ResourceAnnotation{}
	b, x := &b0, m0
	_, _ = b, x
	x.Audience = b.Audience
	x.Priority = b.Priority
	x.LastModified = b.LastModified
	return m0
}

type ResourceDefinition struct {
	state       protoimpl.MessageState `protogen:"hybrid.v1"`
	Uri         *string                `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	Name        *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Title       *string                `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Description *string                `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	MimeType    *string                `protobuf:"bytes,5,opt,name=mime_type,json=mimeType" json:"mime_type,omitempty"`
	Size        *int64                 `protobuf:"varint,6,opt,name=size" json:"size,omitempty"`
	Annotations *ResourceAnnotation    `protobuf:"bytes,7,opt,name=annotations" json:"annotations,omitempty"`
	// Types that are valid to be assigned to ResourceType:
	//
	//	*ResourceDefinition_Static
	//	*ResourceDefinition_Dynamic
	ResourceType isResourceDefinition_ResourceType `protobuf_oneof:"resource_type"`
	// If true, this resource is disabled.
	Disable *bool `protobuf:"varint,10,opt,name=disable" json:"disable,omitempty"`
	// A list of profiles this resource belongs to.
	Profiles      []*Profile `protobuf:"bytes,11,rep,name=profiles" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDefinition) Reset() {
	*x = ResourceDefinition{}
	mi := &file_proto_config_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDefinition) ProtoMessage() {}

func (x *ResourceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceDefinition) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

func (x *ResourceDefinition) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ResourceDefinition) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ResourceDefinition) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ResourceDefinition) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *ResourceDefinition) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *ResourceDefinition) GetAnnotations() *ResourceAnnotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ResourceDefinition) GetResourceType() isResourceDefinition_ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return nil
}

func (x *ResourceDefinition) GetStatic() *StaticResource {
	if x != nil {
		if x, ok := x.ResourceType.(*ResourceDefinition_Static); ok {
			return x.Static
		}
	}
	return nil
}

func (x *ResourceDefinition) GetDynamic() *DynamicResource {
	if x != nil {
		if x, ok := x.ResourceType.(*ResourceDefinition_Dynamic); ok {
			return x.Dynamic
		}
	}
	return nil
}

func (x *ResourceDefinition) GetDisable() bool {
	if x != nil && x.Disable != nil {
		return *x.Disable
	}
	return false
}

func (x *ResourceDefinition) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ResourceDefinition) SetUri(v string) {
	x.Uri = &v
}

func (x *ResourceDefinition) SetName(v string) {
	x.Name = &v
}

func (x *ResourceDefinition) SetTitle(v string) {
	x.Title = &v
}

func (x *ResourceDefinition) SetDescription(v string) {
	x.Description = &v
}

func (x *ResourceDefinition) SetMimeType(v string) {
	x.MimeType = &v
}

func (x *ResourceDefinition) SetSize(v int64) {
	x.Size = &v
}

func (x *ResourceDefinition) SetAnnotations(v *ResourceAnnotation) {
	x.Annotations = v
}

func (x *ResourceDefinition) SetStatic(v *StaticResource) {
	if v == nil {
		x.ResourceType = nil
		return
	}
	x.ResourceType = &ResourceDefinition_Static{v}
}

func (x *ResourceDefinition) SetDynamic(v *DynamicResource) {
	if v == nil {
		x.ResourceType = nil
		return
	}
	x.ResourceType = &ResourceDefinition_Dynamic{v}
}

func (x *ResourceDefinition) SetDisable(v bool) {
	x.Disable = &v
}

func (x *ResourceDefinition) SetProfiles(v []*Profile) {
	x.Profiles = v
}

func (x *ResourceDefinition) HasUri() bool {
	if x == nil {
		return false
	}
	return x.Uri != nil
}

func (x *ResourceDefinition) HasName() bool {
	if x == nil {
		return false
	}
	return x.Name != nil
}

func (x *ResourceDefinition) HasTitle() bool {
	if x == nil {
		return false
	}
	return x.Title != nil
}

func (x *ResourceDefinition) HasDescription() bool {
	if x == nil {
		return false
	}
	return x.Description != nil
}

func (x *ResourceDefinition) HasMimeType() bool {
	if x == nil {
		return false
	}
	return x.MimeType != nil
}

func (x *ResourceDefinition) HasSize() bool {
	if x == nil {
		return false
	}
	return x.Size != nil
}

func (x *ResourceDefinition) HasAnnotations() bool {
	if x == nil {
		return false
	}
	return x.Annotations != nil
}

func (x *ResourceDefinition) HasResourceType() bool {
	if x == nil {
		return false
	}
	return x.ResourceType != nil
}

func (x *ResourceDefinition) HasStatic() bool {
	if x == nil {
		return false
	}
	_, ok := x.ResourceType.(*ResourceDefinition_Static)
	return ok
}

func (x *ResourceDefinition) HasDynamic() bool {
	if x == nil {
		return false
	}
	_, ok := x.ResourceType.(*ResourceDefinition_Dynamic)
	return ok
}

func (x *ResourceDefinition) HasDisable() bool {
	if x == nil {
		return false
	}
	return x.Disable != nil
}

func (x *ResourceDefinition) ClearUri() {
	x.Uri = nil
}

func (x *ResourceDefinition) ClearName() {
	x.Name = nil
}

func (x *ResourceDefinition) ClearTitle() {
	x.Title = nil
}

func (x *ResourceDefinition) ClearDescription() {
	x.Description = nil
}

func (x *ResourceDefinition) ClearMimeType() {
	x.MimeType = nil
}

func (x *ResourceDefinition) ClearSize() {
	x.Size = nil
}

func (x *ResourceDefinition) ClearAnnotations() {
	x.Annotations = nil
}

func (x *ResourceDefinition) ClearResourceType() {
	x.ResourceType = nil
}

func (x *ResourceDefinition) ClearStatic() {
	if _, ok := x.ResourceType.(*ResourceDefinition_Static); ok {
		x.ResourceType = nil
	}
}

func (x *ResourceDefinition) ClearDynamic() {
	if _, ok := x.ResourceType.(*ResourceDefinition_Dynamic); ok {
		x.ResourceType = nil
	}
}

func (x *ResourceDefinition) ClearDisable() {
	x.Disable = nil
}

const ResourceDefinition_ResourceType_not_set_case case_ResourceDefinition_ResourceType = 0
const ResourceDefinition_Static_case case_ResourceDefinition_ResourceType = 8
const ResourceDefinition_Dynamic_case case_ResourceDefinition_ResourceType = 9

func (x *ResourceDefinition) WhichResourceType() case_ResourceDefinition_ResourceType {
	if x == nil {
		return ResourceDefinition_ResourceType_not_set_case
	}
	switch x.ResourceType.(type) {
	case *ResourceDefinition_Static:
		return ResourceDefinition_Static_case
	case *ResourceDefinition_Dynamic:
		return ResourceDefinition_Dynamic_case
	default:
		return ResourceDefinition_ResourceType_not_set_case
	}
}

type ResourceDefinition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Uri         *string
	Name        *string
	Title       *string
	Description *string
	MimeType    *string
	Size        *int64
	Annotations *ResourceAnnotation
	// Fields of oneof ResourceType:
	Static  *StaticResource
	Dynamic *DynamicResource
	// -- end of ResourceType
	// If true, this resource is disabled.
	Disable *bool
	// A list of profiles this resource belongs to.
	Profiles []*Profile
}

func (b0 ResourceDefinition_builder) Build() *ResourceDefinition {
	m0 := &ResourceDefinition{}
	b, x := &b0, m0
	_, _ = b, x
	x.Uri = b.Uri
	x.Name = b.Name
	x.Title = b.Title
	x.Description = b.Description
	x.MimeType = b.MimeType
	x.Size = b.Size
	x.Annotations = b.Annotations
	if b.Static != nil {
		x.ResourceType = &ResourceDefinition_Static{b.Static}
	}
	if b.Dynamic != nil {
		x.ResourceType = &ResourceDefinition_Dynamic{b.Dynamic}
	}
	x.Disable = b.Disable
	x.Profiles = b.Profiles
	return m0
}

type case_ResourceDefinition_ResourceType protoreflect.FieldNumber

func (x case_ResourceDefinition_ResourceType) String() string {
	md := file_proto_config_v1_resource_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isResourceDefinition_ResourceType interface {
	isResourceDefinition_ResourceType()
}

type ResourceDefinition_Static struct {
	Static *StaticResource `protobuf:"bytes,8,opt,name=static,oneof"`
}

type ResourceDefinition_Dynamic struct {
	Dynamic *DynamicResource `protobuf:"bytes,9,opt,name=dynamic,oneof"`
}

func (*ResourceDefinition_Static) isResourceDefinition_ResourceType() {}

func (*ResourceDefinition_Dynamic) isResourceDefinition_ResourceType() {}

type StaticResource struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Types that are valid to be assigned to ContentType:
	//
	//	*StaticResource_TextContent
	//	*StaticResource_BinaryContent
	ContentType   isStaticResource_ContentType `protobuf_oneof:"content_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticResource) Reset() {
	*x = StaticResource{}
	mi := &file_proto_config_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticResource) ProtoMessage() {}

func (x *StaticResource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StaticResource) GetContentType() isStaticResource_ContentType {
	if x != nil {
		return x.ContentType
	}
	return nil
}

func (x *StaticResource) GetTextContent() string {
	if x != nil {
		if x, ok := x.ContentType.(*StaticResource_TextContent); ok {
			return x.TextContent
		}
	}
	return ""
}

func (x *StaticResource) GetBinaryContent() []byte {
	if x != nil {
		if x, ok := x.ContentType.(*StaticResource_BinaryContent); ok {
			return x.BinaryContent
		}
	}
	return nil
}

func (x *StaticResource) SetTextContent(v string) {
	x.ContentType = &StaticResource_TextContent{v}
}

func (x *StaticResource) SetBinaryContent(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.ContentType = &StaticResource_BinaryContent{v}
}

func (x *StaticResource) HasContentType() bool {
	if x == nil {
		return false
	}
	return x.ContentType != nil
}

func (x *StaticResource) HasTextContent() bool {
	if x == nil {
		return false
	}
	_, ok := x.ContentType.(*StaticResource_TextContent)
	return ok
}

func (x *StaticResource) HasBinaryContent() bool {
	if x == nil {
		return false
	}
	_, ok := x.ContentType.(*StaticResource_BinaryContent)
	return ok
}

func (x *StaticResource) ClearContentType() {
	x.ContentType = nil
}

func (x *StaticResource) ClearTextContent() {
	if _, ok := x.ContentType.(*StaticResource_TextContent); ok {
		x.ContentType = nil
	}
}

func (x *StaticResource) ClearBinaryContent() {
	if _, ok := x.ContentType.(*StaticResource_BinaryContent); ok {
		x.ContentType = nil
	}
}

const StaticResource_ContentType_not_set_case case_StaticResource_ContentType = 0
const StaticResource_TextContent_case case_StaticResource_ContentType = 1
const StaticResource_BinaryContent_case case_StaticResource_ContentType = 2

func (x *StaticResource) WhichContentType() case_StaticResource_ContentType {
	if x == nil {
		return StaticResource_ContentType_not_set_case
	}
	switch x.ContentType.(type) {
	case *StaticResource_TextContent:
		return StaticResource_TextContent_case
	case *StaticResource_BinaryContent:
		return StaticResource_BinaryContent_case
	default:
		return StaticResource_ContentType_not_set_case
	}
}

type StaticResource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof ContentType:
	TextContent   *string
	BinaryContent []byte
	// -- end of ContentType
}

func (b0 StaticResource_builder) Build() *StaticResource {
	m0 := &StaticResource{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TextContent != nil {
		x.ContentType = &StaticResource_TextContent{*b.TextContent}
	}
	if b.BinaryContent != nil {
		x.ContentType = &StaticResource_BinaryContent{b.BinaryContent}
	}
	return m0
}

type case_StaticResource_ContentType protoreflect.FieldNumber

func (x case_StaticResource_ContentType) String() string {
	md := file_proto_config_v1_resource_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isStaticResource_ContentType interface {
	isStaticResource_ContentType()
}

type StaticResource_TextContent struct {
	TextContent string `protobuf:"bytes,1,opt,name=text_content,json=textContent,oneof"`
}

type StaticResource_BinaryContent struct {
	BinaryContent []byte `protobuf:"bytes,2,opt,name=binary_content,json=binaryContent,oneof"`
}

func (*StaticResource_TextContent) isStaticResource_ContentType() {}

func (*StaticResource_BinaryContent) isStaticResource_ContentType() {}

type DynamicResource struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Types that are valid to be assigned to CallDefinition:
	//
	//	*DynamicResource_HttpCall
	//	*DynamicResource_GrpcCall
	//	*DynamicResource_WebsocketCall
	//	*DynamicResource_WebrtcCall
	//	*DynamicResource_CommandLineCall
	//	*DynamicResource_McpCall
	CallDefinition isDynamicResource_CallDefinition `protobuf_oneof:"call_definition"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DynamicResource) Reset() {
	*x = DynamicResource{}
	mi := &file_proto_config_v1_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicResource) ProtoMessage() {}

func (x *DynamicResource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_v1_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DynamicResource) GetCallDefinition() isDynamicResource_CallDefinition {
	if x != nil {
		return x.CallDefinition
	}
	return nil
}

func (x *DynamicResource) GetHttpCall() *HttpCallDefinition {
	if x != nil {
		if x, ok := x.CallDefinition.(*DynamicResource_HttpCall); ok {
			return x.HttpCall
		}
	}
	return nil
}

func (x *DynamicResource) GetGrpcCall() *GrpcCallDefinition {
	if x != nil {
		if x, ok := x.CallDefinition.(*DynamicResource_GrpcCall); ok {
			return x.GrpcCall
		}
	}
	return nil
}

func (x *DynamicResource) GetWebsocketCall() *WebsocketCallDefinition {
	if x != nil {
		if x, ok := x.CallDefinition.(*DynamicResource_WebsocketCall); ok {
			return x.WebsocketCall
		}
	}
	return nil
}

func (x *DynamicResource) GetWebrtcCall() *WebrtcCallDefinition {
	if x != nil {
		if x, ok := x.CallDefinition.(*DynamicResource_WebrtcCall); ok {
			return x.WebrtcCall
		}
	}
	return nil
}

func (x *DynamicResource) GetCommandLineCall() *CommandLineCallDefinition {
	if x != nil {
		if x, ok := x.CallDefinition.(*DynamicResource_CommandLineCall); ok {
			return x.CommandLineCall
		}
	}
	return nil
}

func (x *DynamicResource) GetMcpCall() *MCPCallDefinition {
	if x != nil {
		if x, ok := x.CallDefinition.(*DynamicResource_McpCall); ok {
			return x.McpCall
		}
	}
	return nil
}

func (x *DynamicResource) SetHttpCall(v *HttpCallDefinition) {
	if v == nil {
		x.CallDefinition = nil
		return
	}
	x.CallDefinition = &DynamicResource_HttpCall{v}
}

func (x *DynamicResource) SetGrpcCall(v *GrpcCallDefinition) {
	if v == nil {
		x.CallDefinition = nil
		return
	}
	x.CallDefinition = &DynamicResource_GrpcCall{v}
}

func (x *DynamicResource) SetWebsocketCall(v *WebsocketCallDefinition) {
	if v == nil {
		x.CallDefinition = nil
		return
	}
	x.CallDefinition = &DynamicResource_WebsocketCall{v}
}

func (x *DynamicResource) SetWebrtcCall(v *WebrtcCallDefinition) {
	if v == nil {
		x.CallDefinition = nil
		return
	}
	x.CallDefinition = &DynamicResource_WebrtcCall{v}
}

func (x *DynamicResource) SetCommandLineCall(v *CommandLineCallDefinition) {
	if v == nil {
		x.CallDefinition = nil
		return
	}
	x.CallDefinition = &DynamicResource_CommandLineCall{v}
}

func (x *DynamicResource) SetMcpCall(v *MCPCallDefinition) {
	if v == nil {
		x.CallDefinition = nil
		return
	}
	x.CallDefinition = &DynamicResource_McpCall{v}
}

func (x *DynamicResource) HasCallDefinition() bool {
	if x == nil {
		return false
	}
	return x.CallDefinition != nil
}

func (x *DynamicResource) HasHttpCall() bool {
	if x == nil {
		return false
	}
	_, ok := x.CallDefinition.(*DynamicResource_HttpCall)
	return ok
}

func (x *DynamicResource) HasGrpcCall() bool {
	if x == nil {
		return false
	}
	_, ok := x.CallDefinition.(*DynamicResource_GrpcCall)
	return ok
}

func (x *DynamicResource) HasWebsocketCall() bool {
	if x == nil {
		return false
	}
	_, ok := x.CallDefinition.(*DynamicResource_WebsocketCall)
	return ok
}

func (x *DynamicResource) HasWebrtcCall() bool {
	if x == nil {
		return false
	}
	_, ok := x.CallDefinition.(*DynamicResource_WebrtcCall)
	return ok
}

func (x *DynamicResource) HasCommandLineCall() bool {
	if x == nil {
		return false
	}
	_, ok := x.CallDefinition.(*DynamicResource_CommandLineCall)
	return ok
}

func (x *DynamicResource) HasMcpCall() bool {
	if x == nil {
		return false
	}
	_, ok := x.CallDefinition.(*DynamicResource_McpCall)
	return ok
}

func (x *DynamicResource) ClearCallDefinition() {
	x.CallDefinition = nil
}

func (x *DynamicResource) ClearHttpCall() {
	if _, ok := x.CallDefinition.(*DynamicResource_HttpCall); ok {
		x.CallDefinition = nil
	}
}

func (x *DynamicResource) ClearGrpcCall() {
	if _, ok := x.CallDefinition.(*DynamicResource_GrpcCall); ok {
		x.CallDefinition = nil
	}
}

func (x *DynamicResource) ClearWebsocketCall() {
	if _, ok := x.CallDefinition.(*DynamicResource_WebsocketCall); ok {
		x.CallDefinition = nil
	}
}

func (x *DynamicResource) ClearWebrtcCall() {
	if _, ok := x.CallDefinition.(*DynamicResource_WebrtcCall); ok {
		x.CallDefinition = nil
	}
}

func (x *DynamicResource) ClearCommandLineCall() {
	if _, ok := x.CallDefinition.(*DynamicResource_CommandLineCall); ok {
		x.CallDefinition = nil
	}
}

func (x *DynamicResource) ClearMcpCall() {
	if _, ok := x.CallDefinition.(*DynamicResource_McpCall); ok {
		x.CallDefinition = nil
	}
}

const DynamicResource_CallDefinition_not_set_case case_DynamicResource_CallDefinition = 0
const DynamicResource_HttpCall_case case_DynamicResource_CallDefinition = 1
const DynamicResource_GrpcCall_case case_DynamicResource_CallDefinition = 2
const DynamicResource_WebsocketCall_case case_DynamicResource_CallDefinition = 3
const DynamicResource_WebrtcCall_case case_DynamicResource_CallDefinition = 4
const DynamicResource_CommandLineCall_case case_DynamicResource_CallDefinition = 5
const DynamicResource_McpCall_case case_DynamicResource_CallDefinition = 6

func (x *DynamicResource) WhichCallDefinition() case_DynamicResource_CallDefinition {
	if x == nil {
		return DynamicResource_CallDefinition_not_set_case
	}
	switch x.CallDefinition.(type) {
	case *DynamicResource_HttpCall:
		return DynamicResource_HttpCall_case
	case *DynamicResource_GrpcCall:
		return DynamicResource_GrpcCall_case
	case *DynamicResource_WebsocketCall:
		return DynamicResource_WebsocketCall_case
	case *DynamicResource_WebrtcCall:
		return DynamicResource_WebrtcCall_case
	case *DynamicResource_CommandLineCall:
		return DynamicResource_CommandLineCall_case
	case *DynamicResource_McpCall:
		return DynamicResource_McpCall_case
	default:
		return DynamicResource_CallDefinition_not_set_case
	}
}

type DynamicResource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof CallDefinition:
	HttpCall        *HttpCallDefinition
	GrpcCall        *GrpcCallDefinition
	WebsocketCall   *WebsocketCallDefinition
	WebrtcCall      *WebrtcCallDefinition
	CommandLineCall *CommandLineCallDefinition
	McpCall         *MCPCallDefinition
	// -- end of CallDefinition
}

func (b0 DynamicResource_builder) Build() *DynamicResource {
	m0 := &DynamicResource{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HttpCall != nil {
		x.CallDefinition = &DynamicResource_HttpCall{b.HttpCall}
	}
	if b.GrpcCall != nil {
		x.CallDefinition = &DynamicResource_GrpcCall{b.GrpcCall}
	}
	if b.WebsocketCall != nil {
		x.CallDefinition = &DynamicResource_WebsocketCall{b.WebsocketCall}
	}
	if b.WebrtcCall != nil {
		x.CallDefinition = &DynamicResource_WebrtcCall{b.WebrtcCall}
	}
	if b.CommandLineCall != nil {
		x.CallDefinition = &DynamicResource_CommandLineCall{b.CommandLineCall}
	}
	if b.McpCall != nil {
		x.CallDefinition = &DynamicResource_McpCall{b.McpCall}
	}
	return m0
}

type case_DynamicResource_CallDefinition protoreflect.FieldNumber

func (x case_DynamicResource_CallDefinition) String() string {
	md := file_proto_config_v1_resource_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isDynamicResource_CallDefinition interface {
	isDynamicResource_CallDefinition()
}

type DynamicResource_HttpCall struct {
	HttpCall *HttpCallDefinition `protobuf:"bytes,1,opt,name=http_call,json=httpCall,oneof"`
}

type DynamicResource_GrpcCall struct {
	GrpcCall *GrpcCallDefinition `protobuf:"bytes,2,opt,name=grpc_call,json=grpcCall,oneof"`
}

type DynamicResource_WebsocketCall struct {
	WebsocketCall *WebsocketCallDefinition `protobuf:"bytes,3,opt,name=websocket_call,json=websocketCall,oneof"`
}

type DynamicResource_WebrtcCall struct {
	WebrtcCall *WebrtcCallDefinition `protobuf:"bytes,4,opt,name=webrtc_call,json=webrtcCall,oneof"`
}

type DynamicResource_CommandLineCall struct {
	CommandLineCall *CommandLineCallDefinition `protobuf:"bytes,5,opt,name=command_line_call,json=commandLineCall,oneof"`
}

type DynamicResource_McpCall struct {
	McpCall *MCPCallDefinition `protobuf:"bytes,6,opt,name=mcp_call,json=mcpCall,oneof"`
}

func (*DynamicResource_HttpCall) isDynamicResource_CallDefinition() {}

func (*DynamicResource_GrpcCall) isDynamicResource_CallDefinition() {}

func (*DynamicResource_WebsocketCall) isDynamicResource_CallDefinition() {}

func (*DynamicResource_WebrtcCall) isDynamicResource_CallDefinition() {}

func (*DynamicResource_CommandLineCall) isDynamicResource_CallDefinition() {}

func (*DynamicResource_McpCall) isDynamicResource_CallDefinition() {}

var File_proto_config_v1_resource_proto protoreflect.FileDescriptor

const file_proto_config_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/config/v1/resource.proto\x12\x10mcpany.config.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aproto/config/v1/call.proto\x1a\x1dproto/config/v1/profile.proto\"\x8d\x01\n" +
	"\x12ResourceAnnotation\x12\x1a\n" +
	"\baudience\x18\x01 \x03(\tR\baudience\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x01R\bpriority\x12?\n" +
	"\rlast_modified\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified\"\xc8\x03\n" +
	"\x12ResourceDefinition\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12F\n" +
	"\vannotations\x18\a \x01(\v2$.mcpany.config.v1.ResourceAnnotationR\vannotations\x12:\n" +
	"\x06static\x18\b \x01(\v2 .mcpany.config.v1.StaticResourceH\x00R\x06static\x12=\n" +
	"\adynamic\x18\t \x01(\v2!.mcpany.config.v1.DynamicResourceH\x00R\adynamic\x12\x18\n" +
	"\adisable\x18\n" +
	" \x01(\bR\adisable\x125\n" +
	"\bprofiles\x18\v \x03(\v2\x19.mcpany.config.v1.ProfileR\bprofilesB\x0f\n" +
	"\rresource_type\"n\n" +
	"\x0eStaticResource\x12#\n" +
	"\ftext_content\x18\x01 \x01(\tH\x00R\vtextContent\x12'\n" +
	"\x0ebinary_content\x18\x02 \x01(\fH\x00R\rbinaryContentB\x0e\n" +
	"\fcontent_type\"\xea\x03\n" +
	"\x0fDynamicResource\x12C\n" +
	"\thttp_call\x18\x01 \x01(\v2$.mcpany.config.v1.HttpCallDefinitionH\x00R\bhttpCall\x12C\n" +
	"\tgrpc_call\x18\x02 \x01(\v2$.mcpany.config.v1.GrpcCallDefinitionH\x00R\bgrpcCall\x12R\n" +
	"\x0ewebsocket_call\x18\x03 \x01(\v2).mcpany.config.v1.WebsocketCallDefinitionH\x00R\rwebsocketCall\x12I\n" +
	"\vwebrtc_call\x18\x04 \x01(\v2&.mcpany.config.v1.WebrtcCallDefinitionH\x00R\n" +
	"webrtcCall\x12Y\n" +
	"\x11command_line_call\x18\x05 \x01(\v2+.mcpany.config.v1.CommandLineCallDefinitionH\x00R\x0fcommandLineCall\x12@\n" +
	"\bmcp_call\x18\x06 \x01(\v2#.mcpany.config.v1.MCPCallDefinitionH\x00R\amcpCallB\x11\n" +
	"\x0fcall_definitionB7B\rResourceProtoZ&github.com/mcpany/core/proto/config/v1b\beditionsp\xe8\a"

var file_proto_config_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_config_v1_resource_proto_goTypes = []any{
	(*ResourceAnnotation)(nil),        // 0: mcpany.config.v1.ResourceAnnotation
	(*ResourceDefinition)(nil),        // 1: mcpany.config.v1.ResourceDefinition
	(*StaticResource)(nil),            // 2: mcpany.config.v1.StaticResource
	(*DynamicResource)(nil),           // 3: mcpany.config.v1.DynamicResource
	(*timestamppb.Timestamp)(nil),     // 4: google.protobuf.Timestamp
	(*Profile)(nil),                   // 5: mcpany.config.v1.Profile
	(*HttpCallDefinition)(nil),        // 6: mcpany.config.v1.HttpCallDefinition
	(*GrpcCallDefinition)(nil),        // 7: mcpany.config.v1.GrpcCallDefinition
	(*WebsocketCallDefinition)(nil),   // 8: mcpany.config.v1.WebsocketCallDefinition
	(*WebrtcCallDefinition)(nil),      // 9: mcpany.config.v1.WebrtcCallDefinition
	(*CommandLineCallDefinition)(nil), // 10: mcpany.config.v1.CommandLineCallDefinition
	(*MCPCallDefinition)(nil),         // 11: mcpany.config.v1.MCPCallDefinition
}
var file_proto_config_v1_resource_proto_depIdxs = []int32{
	4,  // 0: mcpany.config.v1.ResourceAnnotation.last_modified:type_name -> google.protobuf.Timestamp
	0,  // 1: mcpany.config.v1.ResourceDefinition.annotations:type_name -> mcpany.config.v1.ResourceAnnotation
	2,  // 2: mcpany.config.v1.ResourceDefinition.static:type_name -> mcpany.config.v1.StaticResource
	3,  // 3: mcpany.config.v1.ResourceDefinition.dynamic:type_name -> mcpany.config.v1.DynamicResource
	5,  // 4: mcpany.config.v1.ResourceDefinition.profiles:type_name -> mcpany.config.v1.Profile
	6,  // 5: mcpany.config.v1.DynamicResource.http_call:type_name -> mcpany.config.v1.HttpCallDefinition
	7,  // 6: mcpany.config.v1.DynamicResource.grpc_call:type_name -> mcpany.config.v1.GrpcCallDefinition
	8,  // 7: mcpany.config.v1.DynamicResource.websocket_call:type_name -> mcpany.config.v1.WebsocketCallDefinition
	9,  // 8: mcpany.config.v1.DynamicResource.webrtc_call:type_name -> mcpany.config.v1.WebrtcCallDefinition
	10, // 9: mcpany.config.v1.DynamicResource.command_line_call:type_name -> mcpany.config.v1.CommandLineCallDefinition
	11, // 10: mcpany.config.v1.DynamicResource.mcp_call:type_name -> mcpany.config.v1.MCPCallDefinition
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_config_v1_resource_proto_init() }
func file_proto_config_v1_resource_proto_init() {
	if File_proto_config_v1_resource_proto != nil {
		return
	}
	file_proto_config_v1_call_proto_init()
	file_proto_config_v1_profile_proto_init()
	file_proto_config_v1_resource_proto_msgTypes[1].OneofWrappers = []any{
		(*ResourceDefinition_Static)(nil),
		(*ResourceDefinition_Dynamic)(nil),
	}
	file_proto_config_v1_resource_proto_msgTypes[2].OneofWrappers = []any{
		(*StaticResource_TextContent)(nil),
		(*StaticResource_BinaryContent)(nil),
	}
	file_proto_config_v1_resource_proto_msgTypes[3].OneofWrappers = []any{
		(*DynamicResource_HttpCall)(nil),
		(*DynamicResource_GrpcCall)(nil),
		(*DynamicResource_WebsocketCall)(nil),
		(*DynamicResource_WebrtcCall)(nil),
		(*DynamicResource_CommandLineCall)(nil),
		(*DynamicResource_McpCall)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_v1_resource_proto_rawDesc), len(file_proto_config_v1_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_config_v1_resource_proto_goTypes,
		DependencyIndexes: file_proto_config_v1_resource_proto_depIdxs,
		MessageInfos:      file_proto_config_v1_resource_proto_msgTypes,
	}.Build()
	File_proto_config_v1_resource_proto = out.File
	file_proto_config_v1_resource_proto_goTypes = nil
	file_proto_config_v1_resource_proto_depIdxs = nil
}
