FROM public.ecr.aws/docker/library/golang:1.24 AS builder

WORKDIR /go/src/github.com/ory/hydra
RUN git clone --depth 1 --branch v2.2.0 https://github.com/ory/hydra.git .
RUN go install .

FROM public.ecr.aws/debian/debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /go/bin/hydra /usr/bin/hydra

ENTRYPOINT ["hydra"]
