// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mcpany/core/server/pkg/tool (interfaces: ManagerInterface)
//
// Generated by this command:
//
//	mockgen -destination=pkg/tool/mock_tool_manager.go -package=tool github.com/mcpany/core/server/pkg/tool ManagerInterface
//

// Package tool is a generated GoMock package.
package tool

import (
	context "context"
	reflect "reflect"

	v1 "github.com/mcpany/core/proto/config/v1"
	mcp "github.com/modelcontextprotocol/go-sdk/mcp"
	gomock "go.uber.org/mock/gomock"
)

// Summary: MockManagerInterface represents a data structure.
//
// Parameters:
//   - None
//
// Returns:
//   - None
//
// Errors:
//   - None
//
// Side Effects:
//   - None
type MockManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockManagerInterfaceMockRecorder is the mock recorder for MockManagerInterface.
//
// Summary: MockManagerInterfaceMockRecorder represents a data structure.
//
// Parameters:
//   - None
//
// Returns:
//   - None
//
// Errors:
//   - None
//
// Side Effects:
//   - None
type MockManagerInterfaceMockRecorder struct {
	mock *MockManagerInterface
}

// NewMockManagerInterface creates a new mock instance.
//
// Summary: NewMockManagerInterface executes the operation.
//
// Parameters:
//   - ctrl *gomock.Controller: Input parameter.
//
// Returns:
//   - *MockManagerInterface {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func NewMockManagerInterface(ctrl *gomock.Controller) *MockManagerInterface {
	mock := &MockManagerInterface{ctrl: ctrl}
	mock.recorder = &MockManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
//
// Summary: Returns the recorder for expectations.
//
// Returns:
//   - *MockManagerInterfaceMockRecorder: The recorder.
// Summary: EXPECT executes the operation.
//
// Parameters:
//   - None
//
// Returns:
//   - *MockManagerInterfaceMockRecorder {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) EXPECT() *MockManagerInterfaceMockRecorder {
	return m.recorder
}

// AddMiddleware mocks base method.
//
// Summary: Mock implementation of AddMiddleware.
//
// Parameters:
//   - middleware: ExecutionMiddleware. The middleware to add.
// Summary: AddMiddleware executes the operation.
//
// Parameters:
//   - middleware ExecutionMiddleware: Input parameter.
//
// Returns:
//   - {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) AddMiddleware(middleware ExecutionMiddleware) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMiddleware", middleware)
}

// AddMiddleware indicates an expected call of AddMiddleware.
//
// Summary: Expectation for AddMiddleware.
//
// Parameters:
//   - middleware: any. The expected middleware.
// Summary: AddMiddleware executes the operation.
//
// Parameters:
//   - middleware any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) AddMiddleware(middleware any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMiddleware", reflect.TypeOf((*MockManagerInterface)(nil).AddMiddleware), middleware)
}

// AddServiceInfo mocks base method.
//
// Summary: Mock implementation of AddServiceInfo.
//
// Parameters:
//   - serviceID: string. The service ID.
//   - info: *ServiceInfo. The service info.
// Summary: AddServiceInfo executes the operation.
//
// Parameters:
//   - serviceID string: Input parameter.
//   - info *ServiceInfo: Input parameter.
//
// Returns:
//   - {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) AddServiceInfo(serviceID string, info *ServiceInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddServiceInfo", serviceID, info)
}

// AddServiceInfo indicates an expected call of AddServiceInfo.
//
// Summary: Expectation for AddServiceInfo.
//
// Parameters:
//   - serviceID: any. The expected service ID.
//   - info: any. The expected service info.
// Summary: AddServiceInfo executes the operation.
//
// Parameters:
//   - serviceID: Input parameter.
//   - info any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) AddServiceInfo(serviceID, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddServiceInfo", reflect.TypeOf((*MockManagerInterface)(nil).AddServiceInfo), serviceID, info)
}

// AddTool mocks base method.
//
// Summary: Mock implementation of AddTool.
//
// Parameters:
//   - tool: Tool. The tool to add.
//
// Returns:
//   - error: An error if the operation fails.
// Summary: AddTool executes the operation.
//
// Parameters:
//   - tool Tool: Input parameter.
//
// Returns:
//   - error {
: Result of the operation.
//
// Errors:
//   - Returns an error if the operation fails.
//
// Side Effects:
//   - None
func (m *MockManagerInterface) AddTool(tool Tool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTool", tool)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTool indicates an expected call of AddTool.
//
// Summary: Expectation for AddTool.
//
// Parameters:
//   - tool: any. The expected tool.
//
// Returns:
// Summary: AddTool executes the operation.
//
// Parameters:
//   - tool any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) AddTool(tool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTool", reflect.TypeOf((*MockManagerInterface)(nil).AddTool), tool)
}

// ClearToolsForService mocks base method.
//
// Summary: Mock implementation of ClearToolsForService.
//
// Parameters:
//   - serviceID: string. The service ID.
// Summary: ClearToolsForService executes the operation.
//
// Parameters:
//   - serviceID string: Input parameter.
//
// Returns:
//   - {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) ClearToolsForService(serviceID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearToolsForService", serviceID)
}

// ClearToolsForService indicates an expected call of ClearToolsForService.
//
// Summary: Expectation for ClearToolsForService.
//
// Parameters:
//   - serviceID: any. The expected service ID.
//
// Summary: ClearToolsForService executes the operation.
//
// Parameters:
//   - serviceID any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) ClearToolsForService(serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearToolsForService", reflect.TypeOf((*MockManagerInterface)(nil).ClearToolsForService), serviceID)
}

// ExecuteTool mocks base method.
//
// Summary: Mock implementation of ExecuteTool.
//
// Parameters:
//   - ctx: context.Context. The request context.
//   - req: *ExecutionRequest. The request object.
//
// Summary: ExecuteTool executes the operation.
//
// Parameters:
//   - ctx context.Context: Input parameter.
//   - req *ExecutionRequest: Input parameter.
//
// Returns:
//   - (any, error): Result of the operation.
//
// Errors:
//   - Returns an error if the operation fails.
//
// Side Effects:
//   - None
func (m *MockManagerInterface) ExecuteTool(ctx context.Context, req *ExecutionRequest) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTool", ctx, req)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTool indicates an expected call of ExecuteTool.
//
// Summary: Expectation for ExecuteTool.
//
// Parameters:
//   - ctx: any. The expected context.
//   - req: any. The expected request.
//
// Returns:
//   - *gomock.Call: The mock call.
// Summary: ExecuteTool executes the operation.
//
// Parameters:
//   - ctx: Input parameter.
//   - req any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) ExecuteTool(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTool", reflect.TypeOf((*MockManagerInterface)(nil).ExecuteTool), ctx, req)
}

// GetAllowedServiceIDs mocks base method.
//
// Summary: Mock implementation of GetAllowedServiceIDs.
//
// Parameters:
//   - profileID: string. The profile ID.
//
// Returns:
//   - map[string]bool: The map of allowed service IDs.
// Summary: GetAllowedServiceIDs executes the operation.
//
// Parameters:
//   - profileID string: Input parameter.
//
// Returns:
//   - (map[string]bool, bool): Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) GetAllowedServiceIDs(profileID string) (map[string]bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedServiceIDs", profileID)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetAllowedServiceIDs indicates an expected call of GetAllowedServiceIDs.
//
// Summary: Expectation for GetAllowedServiceIDs.
//
// Parameters:
//   - profileID: any. The expected profile ID.
//
// Returns:
//   - *gomock.Call: The mock call.
// Summary: GetAllowedServiceIDs executes the operation.
//
// Parameters:
//   - profileID any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) GetAllowedServiceIDs(profileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedServiceIDs", reflect.TypeOf((*MockManagerInterface)(nil).GetAllowedServiceIDs), profileID)
}

// GetToolCountForService mocks base method.
//
// Summary: Mock implementation of GetToolCountForService.
//
// Parameters:
//   - serviceID: string. The service ID.
//
// Returns:
// Summary: GetToolCountForService executes the operation.
//
// Parameters:
//   - serviceID string: Input parameter.
//
// Returns:
//   - int {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) GetToolCountForService(serviceID string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolCountForService", serviceID)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetToolCountForService indicates an expected call of GetToolCountForService.
//
// Summary: Expectation for GetToolCountForService.
//
// Parameters:
//   - serviceID: any. The expected service ID.
//
// Returns:
// Summary: GetToolCountForService executes the operation.
//
// Parameters:
//   - serviceID any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) GetToolCountForService(serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolCountForService", reflect.TypeOf((*MockManagerInterface)(nil).GetToolCountForService), serviceID)
}

// GetServiceInfo mocks base method.
//
// Summary: Mock implementation of GetServiceInfo.
//
// Parameters:
//   - serviceID: string. The service ID.
//
// Returns:
// Summary: GetServiceInfo executes the operation.
//
// Parameters:
//   - serviceID string: Input parameter.
//
// Returns:
//   - (*ServiceInfo, bool): Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) GetServiceInfo(serviceID string) (*ServiceInfo, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceInfo", serviceID)
	ret0, _ := ret[0].(*ServiceInfo)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetServiceInfo indicates an expected call of GetServiceInfo.
//
// Summary: Expectation for GetServiceInfo.
//
// Parameters:
//   - serviceID: any. The expected service ID.
//
// Returns:
//   - *gomock.Call: The mock call.
// Summary: GetServiceInfo executes the operation.
//
// Parameters:
//   - serviceID any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) GetServiceInfo(serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceInfo", reflect.TypeOf((*MockManagerInterface)(nil).GetServiceInfo), serviceID)
}

// GetTool mocks base method.
//
// Summary: Mock implementation of GetTool.
//
// Parameters:
//   - toolName: string. The tool name.
//
// Returns:
// Summary: GetTool executes the operation.
//
// Parameters:
//   - toolName string: Input parameter.
//
// Returns:
//   - (Tool, bool): Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) GetTool(toolName string) (Tool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTool", toolName)
	ret0, _ := ret[0].(Tool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetTool indicates an expected call of GetTool.
//
// Summary: Expectation for GetTool.
//
// Parameters:
//   - toolName: any. The expected tool name.
//
// Returns:
//   - *gomock.Call: The mock call.
// Summary: GetTool executes the operation.
//
// Parameters:
//   - toolName any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) GetTool(toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTool", reflect.TypeOf((*MockManagerInterface)(nil).GetTool), toolName)
}

// IsServiceAllowed mocks base method.
//
// Summary: Mock implementation of IsServiceAllowed.
//
// Parameters:
//   - serviceID: string. The service ID.
//   - profileID: string. The profile ID.
//
// Summary: IsServiceAllowed executes the operation.
//
// Parameters:
//   - serviceID: Input parameter.
//   - profileID string: Input parameter.
//
// Returns:
//   - bool {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) IsServiceAllowed(serviceID, profileID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsServiceAllowed", serviceID, profileID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsServiceAllowed indicates an expected call of IsServiceAllowed.
//
// Summary: Expectation for IsServiceAllowed.
//
// Parameters:
//   - serviceID: any. The expected service ID.
//   - profileID: any. The expected profile ID.
//
// Returns:
// Summary: IsServiceAllowed executes the operation.
//
// Parameters:
//   - serviceID: Input parameter.
//   - profileID any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) IsServiceAllowed(serviceID, profileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsServiceAllowed", reflect.TypeOf((*MockManagerInterface)(nil).IsServiceAllowed), serviceID, profileID)
}

// ListMCPTools mocks base method.
//
// Summary: Mock implementation of ListMCPTools.
//
// Returns:
//   - []*mcp.Tool: The list of MCP tools.
// Summary: ListMCPTools executes the operation.
//
// Parameters:
//   - None
//
// Returns:
//   - []*mcp.Tool {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) ListMCPTools() []*mcp.Tool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMCPTools")
	ret0, _ := ret[0].([]*mcp.Tool)
	return ret0
}

// ListMCPTools indicates an expected call of ListMCPTools.
//
// Summary: Expectation for ListMCPTools.
//
// Returns:
//   - *gomock.Call: The mock call.
// Summary: ListMCPTools executes the operation.
//
// Parameters:
//   - None
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) ListMCPTools() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMCPTools", reflect.TypeOf((*MockManagerInterface)(nil).ListMCPTools))
}

// ListServices mocks base method.
//
// Summary: Mock implementation of ListServices.
//
// Returns:
//   - []*ServiceInfo: The list of services.
// Summary: ListServices executes the operation.
//
// Parameters:
//   - None
//
// Returns:
//   - []*ServiceInfo {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) ListServices() []*ServiceInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServices")
	ret0, _ := ret[0].([]*ServiceInfo)
	return ret0
}

// ListServices indicates an expected call of ListServices.
//
// Summary: Expectation for ListServices.
//
// Returns:
//   - *gomock.Call: The mock call.
// Summary: ListServices executes the operation.
//
// Parameters:
//   - None
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) ListServices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServices", reflect.TypeOf((*MockManagerInterface)(nil).ListServices))
}

// ListTools mocks base method.
//
// Summary: Mock implementation of ListTools.
//
// Returns:
// Summary: ListTools executes the operation.
//
// Parameters:
//   - None
//
// Returns:
//   - []Tool {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) ListTools() []Tool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTools")
	ret0, _ := ret[0].([]Tool)
	return ret0
}

// ListTools indicates an expected call of ListTools.
//
// Summary: Expectation for ListTools.
//
// Returns:
// Summary: ListTools executes the operation.
//
// Parameters:
//   - None
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) ListTools() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTools", reflect.TypeOf((*MockManagerInterface)(nil).ListTools))
}

// SetMCPServer mocks base method.
//
// Summary: Mock implementation of SetMCPServer.
//
// Parameters:
// Summary: SetMCPServer executes the operation.
//
// Parameters:
//   - mcpServer MCPServerProvider: Input parameter.
//
// Returns:
//   - {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) SetMCPServer(mcpServer MCPServerProvider) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMCPServer", mcpServer)
}

// SetMCPServer indicates an expected call of SetMCPServer.
//
// Summary: Expectation for SetMCPServer.
//
// Parameters:
// Summary: SetMCPServer executes the operation.
//
// Parameters:
//   - mcpServer any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) SetMCPServer(mcpServer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMCPServer", reflect.TypeOf((*MockManagerInterface)(nil).SetMCPServer), mcpServer)
}

// SetProfiles mocks base method.
//
// Summary: Mock implementation of SetProfiles.
//
// Parameters:
//   - enabled: []string. Enabled profiles.
//   - defs: []*v1.ProfileDefinition. Profile definitions.
// Summary: SetProfiles executes the operation.
//
// Parameters:
//   - enabled []string: Input parameter.
//   - defs []*v1.ProfileDefinition: Input parameter.
//
// Returns:
//   - {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) SetProfiles(enabled []string, defs []*v1.ProfileDefinition) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProfiles", enabled, defs)
}

// SetProfiles indicates an expected call of SetProfiles.
//
// Summary: Expectation for SetProfiles.
//
// Parameters:
//   - enabled: any. The expected enabled profiles.
//   - defs: any. The expected profile definitions.
// Summary: SetProfiles executes the operation.
//
// Parameters:
//   - enabled: Input parameter.
//   - defs any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) SetProfiles(enabled, defs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProfiles", reflect.TypeOf((*MockManagerInterface)(nil).SetProfiles), enabled, defs)
}

// ToolMatchesProfile mocks base method.
//
// Summary: Mock implementation of ToolMatchesProfile.
//
// Parameters:
//   - tool: Tool. The tool.
//   - profileID: string. The profile ID.
//
// Returns:
// Summary: ToolMatchesProfile executes the operation.
//
// Parameters:
//   - tool Tool: Input parameter.
//   - profileID string: Input parameter.
//
// Returns:
//   - bool {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (m *MockManagerInterface) ToolMatchesProfile(tool Tool, profileID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToolMatchesProfile", tool, profileID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ToolMatchesProfile indicates an expected call of ToolMatchesProfile.
//
// Summary: Expectation for ToolMatchesProfile.
//
// Parameters:
//   - tool: any. The expected tool.
//   - profileID: any. The expected profile ID.
//
// Returns:
// Summary: ToolMatchesProfile executes the operation.
//
// Parameters:
//   - tool: Input parameter.
//   - profileID any: Input parameter.
//
// Returns:
//   - *gomock.Call {
: Result of the operation.
//
// Errors:
//   - None
//
// Side Effects:
//   - None
func (mr *MockManagerInterfaceMockRecorder) ToolMatchesProfile(tool, profileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToolMatchesProfile", reflect.TypeOf((*MockManagerInterface)(nil).ToolMatchesProfile), tool, profileID)
}
