# Copyright 2026 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "e2e_test",
    srcs = ["e2e_test.go"],
    data = [
        "//server/cmd/server:server_tarball",
        "//server/tests/integration/cmd/mocks/http_echo_server:http_echo_server_tarball",
    ],
    env = {
        "E2E": "true",
    },
    size = "enormous",
    tags = ["integration"],
)
