// Copyright 2026 Author(s) of MCP Any
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

// InitConfig represents the basic config structure generated by the wizard.
//
// Summary:
//
//	Configuration structure for the generated config file.
//
// Fields:
//   - UpstreamServices: []interface{}. A list of generic service maps.
type InitConfig struct {
	UpstreamServices []interface{} `yaml:"upstream_services"`
}

// newInitCmd creates the init subcommand.
//
// Summary:
//
//	Creates the command to initialize a new MCP Any configuration.
//
// Returns:
//   - *cobra.Command: The configured init command.
func newInitCmd() *cobra.Command {
	var outputPath string

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Interactively initialize a new mcp.yaml configuration file",
		RunE: func(cmd *cobra.Command, args []string) error {
			reader := bufio.NewReader(cmd.InOrStdin())

			fmt.Fprintln(cmd.OutOrStdout(), "Welcome to the MCP Any Configuration Wizard!")
			fmt.Fprintln(cmd.OutOrStdout(), "This will guide you through creating your first mcp.yaml.")
			fmt.Fprintln(cmd.OutOrStdout(), "")

			// 1. Ask for service name
			fmt.Fprint(cmd.OutOrStdout(), "? What is the name of your first service? (e.g. 'my-api'): ")
			name, err := reader.ReadString('\n')
			if err != nil {
				return err
			}
			name = strings.TrimSpace(name)
			if name == "" {
				name = "my-service"
			}

			// 2. Ask for service type
			fmt.Fprintln(cmd.OutOrStdout(), "\n? What type of service is this?")
			fmt.Fprintln(cmd.OutOrStdout(), "  1. HTTP/REST")
			fmt.Fprintln(cmd.OutOrStdout(), "  2. gRPC")
			fmt.Fprintln(cmd.OutOrStdout(), "  3. Stdio (Local Command)")
			fmt.Fprint(cmd.OutOrStdout(), "Enter choice [1]: ")
			choice, err := reader.ReadString('\n')
			if err != nil {
				return err
			}
			choice = strings.TrimSpace(choice)
			if choice == "" {
				choice = "1"
			}

			service := map[string]interface{}{
				"name": name,
			}

			switch choice {
			case "1":
				fmt.Fprint(cmd.OutOrStdout(), "\n? Enter the HTTP base URL (e.g. 'http://localhost:8080'): ")
				address, _ := reader.ReadString('\n')
				service["http_service"] = map[string]interface{}{
					"address": strings.TrimSpace(address),
				}
			case "2":
				fmt.Fprint(cmd.OutOrStdout(), "\n? Enter the gRPC address (e.g. 'localhost:50051'): ")
				address, _ := reader.ReadString('\n')
				service["grpc_service"] = map[string]interface{}{
					"address":        strings.TrimSpace(address),
					"use_reflection": true,
				}
			case "3":
				fmt.Fprint(cmd.OutOrStdout(), "\n? Enter the command to run (e.g. 'python3'): ")
				command, _ := reader.ReadString('\n')
				fmt.Fprint(cmd.OutOrStdout(), "? Enter arguments space-separated (e.g. 'app.py'): ")
				argsStr, _ := reader.ReadString('\n')

				argsList := strings.Fields(strings.TrimSpace(argsStr))

				service["mcp_service"] = map[string]interface{}{
					"stdio_connection": map[string]interface{}{
						"command": strings.TrimSpace(command),
						"args":    argsList,
					},
				}
			default:
				fmt.Fprintln(cmd.OutOrStdout(), "Invalid choice. Creating empty service.")
			}

			cfg := InitConfig{
				UpstreamServices: []interface{}{service},
			}

			yamlData, err := yaml.Marshal(&cfg)
			if err != nil {
				return fmt.Errorf("failed to generate YAML: %w", err)
			}

			if outputPath == "" {
				outputPath = "mcp.yaml"
			}

			err = os.WriteFile(outputPath, yamlData, 0644)
			if err != nil {
				return fmt.Errorf("failed to write file %s: %w", outputPath, err)
			}

			fmt.Fprintf(cmd.OutOrStdout(), "\nSuccess! Generated configuration saved to '%s'\n", outputPath)
			return nil
		},
	}

	cmd.Flags().StringVarP(&outputPath, "output", "o", "mcp.yaml", "Path to save the generated configuration")
	return cmd
}
