--- Dockerfile
+++ Dockerfile
@@ -16,6 +16,8 @@
 COPY ui/ .
 COPY proto/ /proto/
 # Symlink node_modules so proto files can find dependencies during build
 RUN ln -s /app/node_modules /proto/node_modules
-RUN npm run build
+
+# Since Bazel generates the TypeScript bindings dynamically in another step and the raw .proto files are not sufficient
+# to build the UI, we assume 'dist' is built externally before Docker image is assembled, or we use the Bazel 'ui_tarball' target.
