/**
 * Copyright 2026 Author(s) of MCP Any
 * SPDX-License-Identifier: Apache-2.0
 */

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";
import fs from "fs";

// Resolve the proto directory: in a Bazel build it is generated into
// bazel-out and symlinked via bazel-bin; locally it lives one level up.
const localProto = path.join(__dirname, "proto");
// When @proto TS files are generated by Bazel (not checked in) they live under
// bazel-bin/proto which is a symlink to the actual bazel-out directory.
const bazelBinProto = path.join(__dirname, "../bazel-bin/proto");
const fallbackBazelProto = path.join(__dirname, "../bazel-out/k8-fastbuild/bin/proto");
const rootProto = path.join(__dirname, "../proto");
const protoPath = fs.existsSync(fallbackBazelProto) ? fallbackBazelProto : (fs.existsSync(localProto)
  ? localProto
  : fs.existsSync(bazelBinProto)
    ? bazelBinProto
    : fs.existsSync(path.join(__dirname, "../../bazel-out/k8-fastbuild/bin/proto"))
        ? path.join(__dirname, "../../bazel-out/k8-fastbuild/bin/proto")
        : rootProto);

// Resolve the @bufbuild/protobuf/wire sub-path (needed by generated proto files)
const bufbuildWirePath = path.join(
  __dirname,
  "node_modules/.pnpm/@bufbuild+protobuf@2.11.0/node_modules/@bufbuild/protobuf/dist/esm/wire/index.js"
);
const bufbuildWire = fs.existsSync(bufbuildWirePath)
  ? bufbuildWirePath
  : path.join(__dirname, "node_modules/@bufbuild/protobuf/dist/esm/wire/index.js");

export default defineConfig({
  plugins: [react()],
  resolve: {
    // Prevent React (and friends) from being bundled twice when Vite resolves
    // the same package via different paths (e.g. source-tree relative vs Bazel
    // output absolute symlinks). Without this, hooks like useContext fail at
    // runtime because the two React instances don't share their internal
    // dispatcher. react-router-dom is listed here because it's in the root
    // node_modules and is imported transitively from multiple paths; its own
    // node_modules provide the single react-router / @remix-run/router copies.
    dedupe: ["react", "react-dom", "react-router-dom"],
    alias: {
      "@": path.join(__dirname, "src"),
      "@proto": protoPath,
      "@google": path.join(protoPath, "google"),
      "@bufbuild/protobuf/wire": bufbuildWire,
      // grpc-web and browser-headers use CommonJS builds; point Vite at the
      // UMD browser bundle so Rollup can resolve them properly.
      "@improbable-eng/grpc-web": path.join(
        __dirname,
        "node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.umd.js"
      ),
      "browser-headers": path.join(
        __dirname,
        "node_modules/browser-headers/dist/browser-headers.umd.js"
      ),
      // 'long' (required by ts-proto generated code) points to the UMD build
      "long": path.join(__dirname, "node_modules/long/umd/index.js"),
    },
  },
  server: {
    port: 9002,
    // Allow any hostname so that tests accessing via container name or custom
    // hostname (e.g. mcpany-ui) are not blocked by Vite 6.2+ host checking.
    allowedHosts: true,
    // In development, proxy API and gRPC-Web calls to the backend.
    proxy: {
      "/api/v1": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
        ws: true,
      },
      // gRPC-Web: service name segments start with "mcpany."
      "/mcpany.": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/doctor": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/v1/": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/auth/oauth/": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/auth/login": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/debug/": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/sse": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/messages": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/mcp/": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
    },
  },
  // preview.proxy mirrors server.proxy so that `vite preview` (used by
  // Playwright Bazel tests) can reach the backend the same way vite dev does.
  // BACKEND_URL is injected by playwright_test.sh via the webServer.env config.
  preview: {
    // Allow any hostname so that tests accessing via container name
    // (e.g. mcpany-ui:9111) are not blocked by Vite 6.2+ host checking.
    allowedHosts: true,
    proxy: {
      "/api/v1": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
        ws: true,
      },
      "/mcpany.": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/doctor": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/v1/": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/auth/oauth/": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/auth/login": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/debug/": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/sse": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/messages": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
      "/mcp/": {
        target: process.env.BACKEND_URL || "http://localhost:50050",
        changeOrigin: true,
      },
    },
  },
  build: {
    outDir: "dist",
    sourcemap: true,
  },
  css: {
    devSourcemap: true,
  },
});
