name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24'
        cache: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache all dependencies
      uses: actions/cache@v4
      with:
        path: |
          build/venv
          tests/integration/upstream/node_modules
        key: ${{ runner.os }}-deps-${{ hashFiles('requirements.txt', 'tests/integration/upstream/package-lock.json') }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Cache
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Cache Tools
      uses: actions/cache@v4
      with:
        path: build/env/bin
        key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}

    - name: Prepare environment
      run: |
        make prepare         CACHE_TO=type=local,dest=/tmp/.buildx-cache         CACHE_FROM=type=local,src=/tmp/.buildx-cache

    - name: Check linting
      run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24'
        cache: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache all dependencies
      uses: actions/cache@v4
      with:
        path: |
          build/venv
          tests/integration/upstream/node_modules
        key: ${{ runner.os }}-deps-${{ hashFiles('requirements.txt', 'tests/integration/upstream/package-lock.json') }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Cache
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Cache Tools
      uses: actions/cache@v4
      with:
        path: build/env/bin
        key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}

    - name: Prepare environment
      run: make prepare

    - name: test everything
      run: |
        make test         CACHE_TO=type=local,dest=/tmp/.buildx-cache         CACHE_FROM=type=local,src=/tmp/.buildx-cache
