// Copyright 2025 Author(s) of MCP Any
// SPDX-License-Identifier: Apache-2.0

package command

import (
	"context"
	"io"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/image"
	"github.com/docker/docker/api/types/network"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
)

// DockerClient interface matching the subset of docker client methods used.
type DockerClient interface {
	// ImagePull requests the docker host to pull an image from a remote registry.
	//
	// ctx is the context for the request.
	// ref is the ref.
	// options is the options.
	//
	// Returns the result.
	// Returns an error if the operation fails.
	ImagePull(ctx context.Context, ref string, options image.PullOptions) (io.ReadCloser, error)
	// ContainerCreate creates a new container based in the given configuration.
	//
	// ctx is the context for the request.
	// config holds the configuration settings.
	// hostConfig is the hostConfig.
	// networkingConfig is the networkingConfig.
	// platform is the platform.
	// containerName is the containerName.
	//
	// Returns the response.
	// Returns an error if the operation fails.
	ContainerCreate(ctx context.Context, config *container.Config, hostConfig *container.HostConfig, networkingConfig *network.NetworkingConfig, platform *v1.Platform, containerName string) (container.CreateResponse, error)
	// ContainerStart sends a request to the docker daemon to start a container.
	//
	// ctx is the context for the request.
	// containerID is the containerID.
	// options is the options.
	//
	// Returns an error if the operation fails.
	ContainerStart(ctx context.Context, containerID string, options container.StartOptions) error
	// ContainerRemove kills and removes a container from the docker host.
	//
	// ctx is the context for the request.
	// containerID is the containerID.
	// options is the options.
	//
	// Returns an error if the operation fails.
	ContainerRemove(ctx context.Context, containerID string, options container.RemoveOptions) error
	// ContainerLogs returns the logs generated by a container in an io.ReadCloser.
	//
	// ctx is the context for the request.
	// container is the container.
	// options is the options.
	//
	// Returns the result.
	// Returns an error if the operation fails.
	ContainerLogs(ctx context.Context, container string, options container.LogsOptions) (io.ReadCloser, error)
	// ContainerWait waits until the specified container is in a certain state.
	//
	// ctx is the context for the request.
	// containerID is the containerID.
	// condition is the condition.
	//
	// Returns the response.
	// Returns the result.
	ContainerWait(ctx context.Context, containerID string, condition container.WaitCondition) (<-chan container.WaitResponse, <-chan error)
	// ContainerAttach attaches to a container to read its output or write input.
	//
	// ctx is the context for the request.
	// container is the container.
	// options is the options.
	//
	// Returns the response.
	// Returns an error if the operation fails.
	ContainerAttach(ctx context.Context, container string, options container.AttachOptions) (types.HijackedResponse, error)
	// Close closes the client and releases any associated resources.
	//
	// Returns an error if the operation fails.
	Close() error
}
