// Copyright 2025 Author(s) of MCP Any
// SPDX-License-Identifier: Apache-2.0

package command

import (
	"context"
	"io"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/image"
	"github.com/docker/docker/api/types/network"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
)

// DockerClient interface matching the subset of docker client methods used.
type DockerClient interface {
	// ImagePull requests the docker host to pull an image from a remote registry.
	//
	// Parameters:
	//   - ctx: context.Context. The context for the request.
	//   - ref: string. The image reference (e.g., "alpine:latest").
	//   - options: image.PullOptions. Options for pulling the image.
	//
	// Returns:
	//   - io.ReadCloser: The response body from the Docker API.
	//   - error: An error if the operation fails.
	ImagePull(ctx context.Context, ref string, options image.PullOptions) (io.ReadCloser, error)
	// ContainerCreate creates a new container based in the given configuration.
	//
	// Parameters:
	//   - ctx: context.Context. The context for the request.
	//   - config: *container.Config. The container configuration.
	//   - hostConfig: *container.HostConfig. The host configuration.
	//   - networkingConfig: *network.NetworkingConfig. The network configuration.
	//   - platform: *v1.Platform. The platform configuration.
	//   - containerName: string. The name of the container.
	//
	// Returns:
	//   - container.CreateResponse: The response containing the container ID.
	//   - error: An error if the operation fails.
	ContainerCreate(ctx context.Context, config *container.Config, hostConfig *container.HostConfig, networkingConfig *network.NetworkingConfig, platform *v1.Platform, containerName string) (container.CreateResponse, error)
	// ContainerStart sends a request to the docker daemon to start a container.
	//
	// Parameters:
	//   - ctx: context.Context. The context for the request.
	//   - containerID: string. The ID of the container to start.
	//   - options: container.StartOptions. Options for starting the container.
	//
	// Returns:
	//   - error: An error if the operation fails.
	ContainerStart(ctx context.Context, containerID string, options container.StartOptions) error
	// ContainerRemove kills and removes a container from the docker host.
	//
	// Parameters:
	//   - ctx: context.Context. The context for the request.
	//   - containerID: string. The ID of the container to remove.
	//   - options: container.RemoveOptions. Options for removing the container.
	//
	// Returns:
	//   - error: An error if the operation fails.
	ContainerRemove(ctx context.Context, containerID string, options container.RemoveOptions) error
	// ContainerLogs returns the logs generated by a container in an io.ReadCloser.
	//
	// Parameters:
	//   - ctx: context.Context. The context for the request.
	//   - container: string. The ID or name of the container.
	//   - options: container.LogsOptions. Options for fetching logs.
	//
	// Returns:
	//   - io.ReadCloser: The logs stream.
	//   - error: An error if the operation fails.
	ContainerLogs(ctx context.Context, container string, options container.LogsOptions) (io.ReadCloser, error)
	// ContainerWait waits until the specified container is in a certain state.
	//
	// Parameters:
	//   - ctx: context.Context. The context for the request.
	//   - containerID: string. The ID of the container to wait for.
	//   - condition: container.WaitCondition. The condition to wait for.
	//
	// Returns:
	//   - <-chan container.WaitResponse: A channel receiving the wait response.
	//   - <-chan error: A channel receiving errors.
	ContainerWait(ctx context.Context, containerID string, condition container.WaitCondition) (<-chan container.WaitResponse, <-chan error)
	// ContainerAttach attaches to a container to read its output or write input.
	//
	// Parameters:
	//   - ctx: context.Context. The context for the request.
	//   - container: string. The ID or name of the container.
	//   - options: container.AttachOptions. Options for attaching.
	//
	// Returns:
	//   - types.HijackedResponse: The hijacked connection response.
	//   - error: An error if the operation fails.
	ContainerAttach(ctx context.Context, container string, options container.AttachOptions) (types.HijackedResponse, error)
	// Close closes the client and releases any associated resources.
	//
	// Returns:
	//   - error: An error if the operation fails.
	Close() error
}
